const galleryImages = [
  ['compounding-workshop.webp', 1400, 1050, true],
  ['filling-line.webp', 1400, 637, false],
  ['quality-inspection.webp', 1400, 637, false],
  ['packing-team.webp', 1400, 637, false],
  ['compounding-tanks.webp', 1400, 637, true],
  ['team-office.webp', 1400, 637, false],
  ['sample-showroom.webp', 1400, 637, false],
  ['warehouse.webp', 1400, 1050, false]
];

function gallery(items) {
  return items.map((item, index) => ({
    ...item,
    image: galleryImages[index][0], width: galleryImages[index][1], height: galleryImages[index][2], wide: galleryImages[index][3]
  }));
}

module.exports = {
  en: {
    hero: { location: '', title: 'A Real Manufacturing Partner Behind Your Fragrance Brand', text: 'From fragrance compounding and filling to packaging assembly and export preparation, our facility supports private label, OEM and ODM fragrance projects.', cta: 'Request a Factory Video Call', alt: '{brand} manufacturing facility building in Guangzhou' },
    entity: { kicker: 'Who We Are', title: 'An International B2B Program Built on Real Production', paragraphs: ['Founded in {{config.brand.founded.long}}, {{config.brand.name}} is an international B2B perfume manufacturing program for brand owners, importers and distributors worldwide.', 'Our project team coordinates international inquiries, fragrance direction, component selection, manufacturing and export preparation through one workflow. Production is carried out by {{config.manufacturer.legalName}} at its perfume manufacturing facility in Baiyun District, Guangzhou.', '{{config.transaction.entityNotice.en}}'], facts: [['Business Program', '{{config.brand.name}}'], ['Program Positioning', 'International B2B Perfume Manufacturing'], ['Manufacturing Entity', '{{config.manufacturer.legalName}}'], ['Established', '{{config.brand.founded.long}}'], ['Manufacturing Location', '{{config.manufacturer.location.full}}'], ['Service Models', 'Private Label · OEM · ODM']] },
    metricLabels: ['Factory Area', 'Established', 'Controlled Workshop', 'Fragrance Formula Library'],
    video: { kicker: 'Factory Walkthrough', title: 'See the Facility Behind the Website', text: 'Watch a short walkthrough of our production environment. For a live view of current equipment and capacity, request a scheduled video call with our team.', fallback: 'Your browser does not support embedded video.', label: 'Factory Walkthrough', meta: 'Real production environment · Guangzhou' },
    gallery: {
      kicker: 'Inside the Facility', title: 'A Practical View of How We Work', text: 'Real photographs from our office, production, filling, inspection, sample and storage areas.', items: gallery([
        { alt: 'Stainless-steel fragrance compounding equipment in the production workshop', title: 'Compounding Workshop', text: 'Stainless-steel preparation equipment' },
        { alt: 'Perfume filling and component assembly equipment', title: 'Filling Equipment', text: 'Product filling and component handling' },
        { alt: 'Production team conducting packaging and quality inspection', title: 'Quality Inspection', text: 'In-process checking and coding' },
        { alt: 'Factory team completing perfume packaging assembly', title: 'Packaging Assembly', text: 'Manual inspection and secondary packing' },
        { alt: 'Large stainless-steel processing tanks in a controlled workshop', title: 'Processing Tanks', text: 'Controlled batch preparation' },
        { alt: '{brand} project and business support team at work', title: 'Project Support', text: 'Quoting, sampling and order coordination' },
        { alt: 'Fragrance and packaging sample display area', title: 'Sample Showroom', text: 'Bottle and product reference library' },
        { alt: 'Packaging materials and finished goods staging warehouse', title: 'Storage & Staging', text: 'Packaging materials and shipment preparation' }
      ])
    },
    workflow: { kicker: 'Production Workflow', title: 'Defined Stages, Visible Responsibility', text: 'Automated equipment is combined with manual inspection and secondary packaging, giving each project clear approval and control points.', items: [['Material Preparation', 'Formula, alcohol and approved components are prepared against the project specification.'], ['Compounding', 'Fragrance batches are mixed in stainless-steel processing equipment.'], ['Maceration & Filtration', 'The batch is conditioned and filtered according to the production plan.'], ['Filling & Crimping', 'Bottles move through filling, pump placement and sealing operations.'], ['Inspection & Packing', 'Finished packs receive visual, coding and assembly checks.'], ['Shipment Staging', 'Goods are packed and prepared for the confirmed freight route.']] },
    certificates: { kicker: 'Certification & Licensing', title: 'Documents Available for Buyer Verification', intro: 'To prevent unauthorized reuse, the previews below are intentionally low-resolution and blurred. Full copies are supplied to qualified buyers on request.', protected: 'Protected Preview', request: 'Full Copy on Request', cards: [['SGS · System Certification', 'ISO 22716', 'Cosmetics Good Manufacturing Practices. Current certificate period shown in our verification copy: {{config.certificates.iso22716.validityDisplay}}.', 'iso-22716-preview.webp', 'Protected blurred preview of ISO 22716 certificate', 480, 679], ['SGS · GMP Assessment', 'Cosmetic GMP Compliance', 'SGS-audited assessment against U.S. FDA CFSAN Cosmetic GMP Guidelines. This is not presented as FDA product approval.', 'gmp-preview.webp', 'Protected blurred preview of cosmetic GMP assessment document', 480, 679], ['Guangdong Medical Products Administration', 'Cosmetics Manufacturing License', 'Manufacturing license issued by the provincial regulator. Current license validity shown in our verification copy extends through {{config.certificates.manufacturingLicense.validThroughDisplay}}.', 'production-license-preview.webp', 'Protected blurred preview of cosmetics manufacturing license', 560, 396]], ctaTitle: 'Need Documents for Supplier Approval?', ctaText: 'Send your company name, destination market and planned product category. Our team will provide the relevant full documents for verification.', cta: 'Request Full Certificates' }
  },
  'zh-CN': {
    hero: { location: '', title: '了解 {brand} 的生产工厂', text: '从香精调配、灌装到包装组装和出口准备，为私人标签、OEM 与 ODM 香氛项目提供可核验的生产支持。', cta: '预约工厂视频沟通', alt: '广州香水生产场地外观' },
    entity: { kicker: '我们是谁', title: '立足真实生产的国际 B2B 项目', paragraphs: ['{{site.brand.name}} 是面向全球品牌方、进口商和分销商的国际 B2B 香水制造项目。', '项目团队通过统一流程协调海外询盘、香型方向、组件选择、生产和出口准备。香水生产由 {{site.manufacturer.legalName}} 在广州白云区生产场地完成。', '{{site.transaction.entityNotice.zh}}'], facts: [['业务项目', '{{site.brand.name}}'], ['项目定位', '国际 B2B 香水制造'], ['生产主体', '{{site.manufacturer.legalName}}'], ['成立时间', '{{fact("founded")}}'], ['生产地点', '{{site.manufacturer.location.full}}'], ['合作方式', '私人标签 · OEM · ODM']] },
    metricLabels: ['厂房面积', '成立时间', '受控车间', '香精配方库'],
    video: { kicker: '工厂实景', title: '查看网站背后的生产场地', text: '通过短片了解实际生产环境。如需实时查看当前设备和产能，可预约与项目团队进行工厂视频沟通。', fallback: '您的浏览器不支持嵌入视频。', label: '工厂实景短片', meta: '真实生产环境 · 广州' },
    gallery: {
      kicker: '走进工厂', title: '了解我们的实际工作环境', text: '展示办公室、生产、灌装、检验、样品和仓储区域的真实照片。', items: gallery([
        { alt: '生产车间内的不锈钢香水调配设备', title: '调配车间', text: '不锈钢配制设备' },
        { alt: '香水灌装和组件装配设备', title: '灌装设备', text: '产品灌装与组件处理' },
        { alt: '生产团队进行包装和质量检查', title: '质量检验', text: '过程检查与喷码' },
        { alt: '工厂团队完成香水包装装配', title: '包装装配', text: '人工检查与二次包装' },
        { alt: '受控车间内的大型不锈钢处理罐', title: '工艺罐体', text: '受控批次配制' },
        { alt: '{brand} 项目和业务支持团队工作现场', title: '项目支持', text: '报价、打样与订单协调' },
        { alt: '香型和包装样品展示区域', title: '样品展示区', text: '瓶器与产品参考资料库' },
        { alt: '包装材料和成品暂存仓库', title: '仓储与暂存', text: '包装材料与出货准备' }
      ])
    },
    workflow: { kicker: '生产流程', title: '明确阶段与清晰责任', text: '自动化设备结合人工检验和二次包装，为每个项目设置清晰的批准与控制节点。', items: [['材料准备', '按照项目规格准备配方、酒精和批准组件。'], ['调配', '使用不锈钢工艺设备混合香水批次。'], ['熟化与过滤', '按照生产计划对批次进行静置和过滤。'], ['灌装与压口', '瓶器依次完成灌装、泵头安装和封口。'], ['检验与包装', '检查成品外观、编码和装配。'], ['出货暂存', '完成装箱，并为确认的运输路线做好准备。']] },
    certificates: { kicker: '供应商核验', title: '可供采购方核验的证书文件', intro: '为避免证书被未经授权复用，公开页面仅展示模糊或低分辨率预览。合格采购方可联系项目团队申请完整副本。', protected: '受保护预览', request: '完整副本需申请', cards: [['SGS · 体系认证', 'ISO 22716', '当前核验副本显示的有效期为 {{site.certificates.iso22716.validityDisplayZh}}。', 'iso-22716-preview.webp', 'ISO 22716 证书受保护预览', 480, 679], ['SGS · GMP 评估', '化妆品 GMP 评估', '该评估不代表 FDA 对具体产品的批准。', 'gmp-preview.webp', 'GMP 评估文件受保护预览', 480, 679], ['广东省药品监督管理部门', '化妆品生产许可证', '当前核验副本显示有效期至 {{site.certificates.manufacturingLicense.validThroughDisplayZh}}。', 'production-license-preview.webp', '化妆品生产许可证受保护预览', 560, 396]], ctaTitle: '供应商审核需要完整文件？', ctaText: '请提供公司名称、目标市场和计划产品类别，项目团队将发送相关文件供核验。', cta: '申请完整核验文件' }
  },
  es: {
    hero: { location: '', title: 'Un Socio de Fabricación Real Detrás de su Marca de Perfumería', text: 'Desde la composición y el llenado hasta el ensamblaje del envase y la preparación para la exportación, nuestras instalaciones respaldan proyectos de perfumería de marca privada, OEM y ODM.', cta: 'Solicitar una Videollamada desde la Fábrica', alt: 'Edificio de las instalaciones de fabricación de {brand} en Guangzhou' },
    entity: { kicker: 'Quiénes Somos', title: 'Un Programa Internacional B2B Basado en Producción Real', paragraphs: ['Fundada en {{config.brand.founded.long}}, {{config.brand.name}} es un programa internacional B2B de fabricación de perfumes para propietarios de marcas, importadores y distribuidores de todo el mundo.', 'Nuestro equipo coordina consultas internacionales, orientación olfativa, selección de componentes, fabricación y preparación para la exportación mediante un único flujo de trabajo. La producción corre a cargo de {{config.manufacturer.legalName}} en sus instalaciones de fabricación de perfumes del distrito de Baiyun, Guangzhou.', '{{config.transaction.entityNotice.en}}'], facts: [['Programa Comercial', '{{config.brand.name}}'], ['Posicionamiento del Programa', 'Fabricación Internacional B2B de Perfumes'], ['Entidad Fabricante', '{{config.manufacturer.legalName}}'], ['Fundada', '{{config.brand.founded.long}}'], ['Ubicación de Fabricación', '{{config.manufacturer.location.full}}'], ['Modalidades de Servicio', 'Marca privada · OEM · ODM']] },
    metricLabels: ['Superficie de la Fábrica', 'Fundada', 'Taller Controlado', 'Biblioteca de Fórmulas de Fragancias'],
    video: { kicker: 'Recorrido por la Fábrica', title: 'Conozca las Instalaciones Detrás del Sitio Web', text: 'Vea un breve recorrido por nuestro entorno de producción. Para observar en directo los equipos y la capacidad actuales, solicite una videollamada programada con nuestro equipo.', fallback: 'Su navegador no admite vídeo incrustado.', label: 'Recorrido por la Fábrica', meta: 'Entorno de producción real · Guangzhou' },
    gallery: { kicker: 'Dentro de las Instalaciones', title: 'Una Visión Práctica de Cómo Trabajamos', text: 'Fotografías reales de nuestras áreas de oficina, producción, llenado, inspección, muestras y almacenamiento.', items: gallery([
      { alt: 'Equipos de acero inoxidable para la composición de fragancias en el taller de producción', title: 'Taller de Composición', text: 'Equipos de preparación de acero inoxidable' },
      { alt: 'Equipos de llenado de perfumes y ensamblaje de componentes', title: 'Equipos de Llenado', text: 'Llenado de producto y manipulación de componentes' },
      { alt: 'Equipo de producción realizando inspecciones de envases y calidad', title: 'Inspección de Calidad', text: 'Controles en proceso y codificación' },
      { alt: 'Equipo de fábrica completando el ensamblaje de envases de perfume', title: 'Ensamblaje de Envases', text: 'Inspección manual y embalaje secundario' },
      { alt: 'Grandes tanques de proceso de acero inoxidable en un taller controlado', title: 'Tanques de Proceso', text: 'Preparación controlada de lotes' },
      { alt: 'Equipo de proyectos y asistencia comercial de {brand} trabajando', title: 'Asistencia de Proyectos', text: 'Cotización, muestreo y coordinación de pedidos' },
      { alt: 'Área de exposición de muestras de fragancias y envases', title: 'Sala de Muestras', text: 'Biblioteca de referencia de frascos y productos' },
      { alt: 'Almacén de preparación de materiales de envase y productos terminados', title: 'Almacenamiento y Preparación', text: 'Materiales de envase y preparación de expediciones' }
    ]) },
    workflow: { kicker: 'Flujo de Producción', title: 'Etapas Definidas, Responsabilidad Visible', text: 'Los equipos automatizados se combinan con la inspección manual y el embalaje secundario, proporcionando a cada proyecto puntos claros de aprobación y control.', items: [['Preparación de Materiales', 'La fórmula, el alcohol y los componentes aprobados se preparan conforme a las especificaciones del proyecto.'], ['Composición', 'Los lotes de fragancia se mezclan en equipos de proceso de acero inoxidable.'], ['Maceración y Filtración', 'El lote se acondiciona y filtra según el plan de producción.'], ['Llenado y Engastado', 'Los frascos pasan por las operaciones de llenado, colocación de bomba y sellado.'], ['Inspección y Embalaje', 'Los envases terminados se someten a controles visuales, de codificación y ensamblaje.'], ['Preparación de la Expedición', 'La mercancía se embala y prepara para la ruta de transporte confirmada.']] },
    certificates: { kicker: 'Certificación y Licencias', title: 'Documentos Disponibles para la Verificación del Comprador', intro: 'Para evitar la reutilización no autorizada, las vistas previas siguientes se muestran intencionadamente en baja resolución y desenfocadas. Se facilitan copias completas a compradores cualificados previa solicitud.', protected: 'Vista Previa Protegida', request: 'Copia Completa Previa Solicitud', cards: [['SGS · Certificación del Sistema', 'ISO 22716', 'Buenas Prácticas de Fabricación de Cosméticos. Periodo actual del certificado indicado en nuestra copia de verificación: {{config.certificates.iso22716.validityDisplay}}.', 'iso-22716-preview.webp', 'Vista previa protegida y desenfocada del certificado ISO 22716', 480, 679], ['SGS · Evaluación GMP', 'Cumplimiento de GMP Cosméticas', 'Evaluación auditada por SGS conforme a las directrices de GMP para cosméticos de la CFSAN de la FDA de EE. UU. No se presenta como una aprobación de producto por la FDA.', 'gmp-preview.webp', 'Vista previa protegida y desenfocada del documento de evaluación GMP cosmética', 480, 679], ['Administración de Productos Médicos de Guangdong', 'Licencia de Fabricación de Cosméticos', 'Licencia de fabricación expedida por el organismo regulador provincial. La vigencia actual indicada en nuestra copia de verificación se extiende hasta {{config.certificates.manufacturingLicense.validThroughDisplay}}.', 'production-license-preview.webp', 'Vista previa protegida y desenfocada de la licencia de fabricación de cosméticos', 560, 396]], ctaTitle: '¿Necesita Documentos para Homologar al Proveedor?', ctaText: 'Envíenos el nombre de su empresa, el mercado de destino y la categoría de producto prevista. Nuestro equipo facilitará los documentos completos pertinentes para su verificación.', cta: 'Solicitar Certificados Completos' }
  },
  ar: {
    hero: { location: '', title: 'شريك تصنيع حقيقي يقف خلف علامتك التجارية للعطور', text: 'من تركيب العطور والتعبئة إلى تجميع العبوات والتحضير للتصدير، تدعم منشأتنا مشاريع العطور بالعلامة الخاصة وOEM وODM.', cta: 'طلب مكالمة فيديو من المصنع', alt: 'مبنى منشأة تصنيع {brand} في غوانغجو' },
    entity: { kicker: 'من نحن', title: 'برنامج دولي B2B قائم على إنتاج حقيقي', paragraphs: ['تأسست {{config.brand.name}} في {{config.brand.founded.long}}، وهي برنامج دولي B2B لتصنيع العطور يخدم مالكي العلامات التجارية والمستوردين والموزعين حول العالم.', 'ينسق فريق المشاريع الاستفسارات الدولية والتوجه العطري واختيار المكونات والتصنيع والتحضير للتصدير ضمن سير عمل موحد. وتتولى {{config.manufacturer.legalName}} الإنتاج في منشأة تصنيع العطور التابعة لها في مقاطعة باييون، غوانغجو.', '{{config.transaction.entityNotice.en}}'], facts: [['البرنامج التجاري', '{{config.brand.name}}'], ['تموضع البرنامج', 'تصنيع عطور دولي B2B'], ['جهة التصنيع', '{{config.manufacturer.legalName}}'], ['سنة التأسيس', '{{config.brand.founded.long}}'], ['موقع التصنيع', '{{config.manufacturer.location.full}}'], ['نماذج الخدمة', 'علامة خاصة · OEM · ODM']] },
    metricLabels: ['مساحة المصنع', 'سنة التأسيس', 'ورشة خاضعة للرقابة', 'مكتبة تركيبات العطور'],
    video: { kicker: 'جولة في المصنع', title: 'شاهد المنشأة القائمة خلف الموقع', text: 'شاهد جولة قصيرة في بيئة الإنتاج لدينا. وللاطلاع المباشر على المعدات والطاقة الإنتاجية الحالية، اطلب مكالمة فيديو مجدولة مع فريقنا.', fallback: 'متصفحك لا يدعم الفيديو المضمن.', label: 'جولة في المصنع', meta: 'بيئة إنتاج حقيقية · غوانغجو' },
    gallery: { kicker: 'داخل المنشأة', title: 'نظرة عملية على طريقة عملنا', text: 'صور حقيقية من مناطق المكتب والإنتاج والتعبئة والفحص والعينات والتخزين لدينا.', items: gallery([
      { alt: 'معدات من الفولاذ المقاوم للصدأ لتركيب العطور في ورشة الإنتاج', title: 'ورشة التركيب', text: 'معدات تحضير من الفولاذ المقاوم للصدأ' },
      { alt: 'معدات تعبئة العطور وتجميع المكونات', title: 'معدات التعبئة', text: 'تعبئة المنتج ومناولة المكونات' },
      { alt: 'فريق الإنتاج يجري فحص العبوات والجودة', title: 'فحص الجودة', text: 'الفحص أثناء العملية والترميز' },
      { alt: 'فريق المصنع يستكمل تجميع عبوات العطور', title: 'تجميع العبوات', text: 'فحص يدوي وتغليف ثانوي' },
      { alt: 'خزانات معالجة كبيرة من الفولاذ المقاوم للصدأ في ورشة خاضعة للرقابة', title: 'خزانات المعالجة', text: 'تحضير مضبوط للدفعات' },
      { alt: 'فريق دعم المشاريع والأعمال في {brand} أثناء العمل', title: 'دعم المشاريع', text: 'عروض الأسعار والعينات وتنسيق الطلبات' },
      { alt: 'منطقة عرض عينات العطور والعبوات', title: 'صالة العينات', text: 'مكتبة مرجعية للزجاجات والمنتجات' },
      { alt: 'مستودع تجهيز مواد العبوات والمنتجات النهائية', title: 'التخزين والتجهيز', text: 'مواد العبوات والتحضير للشحن' }
    ]) },
    workflow: { kicker: 'سير عمل الإنتاج', title: 'مراحل محددة ومسؤوليات واضحة', text: 'تتكامل المعدات الآلية مع الفحص اليدوي والتغليف الثانوي، ما يمنح كل مشروع نقاط اعتماد ورقابة واضحة.', items: [['تحضير المواد', 'تُحضّر التركيبة والكحول والمكونات المعتمدة وفق مواصفات المشروع.'], ['التركيب', 'تُمزج دفعات العطر في معدات معالجة من الفولاذ المقاوم للصدأ.'], ['التعتيق والترشيح', 'تُكيّف الدفعة وتُرشح وفق خطة الإنتاج.'], ['التعبئة والكبس', 'تمر الزجاجات بعمليات التعبئة وتركيب المضخة والإغلاق.'], ['الفحص والتغليف', 'تخضع العبوات النهائية لفحوص بصرية وفحوص الترميز والتجميع.'], ['تجهيز الشحنة', 'تُعبأ البضائع وتُجهز لمسار الشحن المؤكد.']] },
    certificates: { kicker: 'الشهادات والتراخيص', title: 'مستندات متاحة لتحقق المشتري', intro: 'لمنع إعادة الاستخدام غير المصرح بها، تُعرض المعاينات أدناه عمدًا بدقة منخفضة وبصورة مطموسة. وتُقدم النسخ الكاملة للمشترين المؤهلين عند الطلب.', protected: 'معاينة محمية', request: 'النسخة الكاملة عند الطلب', cards: [['SGS · شهادة النظام', 'ISO 22716', 'ممارسات التصنيع الجيد لمستحضرات التجميل. فترة الشهادة الحالية المبينة في نسخة التحقق لدينا: {{config.certificates.iso22716.validityDisplay}}.', 'iso-22716-preview.webp', 'معاينة محمية ومطموسة لشهادة ISO 22716', 480, 679], ['SGS · تقييم GMP', 'الامتثال لممارسات GMP لمستحضرات التجميل', 'تقييم مدقق من SGS وفق إرشادات GMP لمستحضرات التجميل الصادرة عن CFSAN التابعة لـ FDA الأمريكية. ولا يُعرض باعتباره اعتماد منتج من FDA.', 'gmp-preview.webp', 'معاينة محمية ومطموسة لوثيقة تقييم GMP لمستحضرات التجميل', 480, 679], ['إدارة المنتجات الطبية في غوانغدونغ', 'ترخيص تصنيع مستحضرات التجميل', 'ترخيص تصنيع صادر عن الجهة التنظيمية الإقليمية. تمتد الصلاحية الحالية المبينة في نسخة التحقق لدينا حتى {{config.certificates.manufacturingLicense.validThroughDisplay}}.', 'production-license-preview.webp', 'معاينة محمية ومطموسة لترخيص تصنيع مستحضرات التجميل', 560, 396]], ctaTitle: 'هل تحتاج إلى مستندات لاعتماد المورد؟', ctaText: 'أرسل اسم شركتك والسوق المستهدف وفئة المنتج المخطط لها. سيقدم فريقنا المستندات الكاملة ذات الصلة للتحقق.', cta: 'طلب الشهادات الكاملة' }
  },
  fr: {
    hero: { location: '', title: 'Un Véritable Partenaire Industriel Derrière Votre Marque de Parfums', text: 'De la composition et du remplissage à l’assemblage du packaging et à la préparation export, notre site accompagne les projets de parfumerie en marque blanche, OEM et ODM.', cta: 'Demander une Visite Vidéo de l’Usine', alt: 'Bâtiment du site de fabrication de {brand} à Guangzhou' },
    entity: { kicker: 'Qui Sommes-Nous', title: 'Un Programme International B2B Fondé sur une Production Réelle', paragraphs: ['Fondée en {{config.brand.founded.long}}, {{config.brand.name}} est un programme international B2B de fabrication de parfums destiné aux propriétaires de marques, importateurs et distributeurs du monde entier.', 'Notre équipe projets coordonne les demandes internationales, l’orientation olfactive, la sélection des composants, la fabrication et la préparation export dans un flux de travail unique. La production est assurée par {{config.manufacturer.legalName}} sur son site de fabrication de parfums situé dans le district de Baiyun, à Guangzhou.', '{{config.transaction.entityNotice.en}}'], facts: [['Programme Commercial', '{{config.brand.name}}'], ['Positionnement du Programme', 'Fabrication Internationale B2B de Parfums'], ['Entité de Fabrication', '{{config.manufacturer.legalName}}'], ['Fondation', '{{config.brand.founded.long}}'], ['Site de Fabrication', '{{config.manufacturer.location.full}}'], ['Modèles de Service', 'Marque blanche · OEM · ODM']] },
    metricLabels: ['Surface de l’Usine', 'Fondation', 'Atelier Contrôlé', 'Bibliothèque de Formules Olfactives'],
    video: { kicker: 'Visite de l’Usine', title: 'Découvrez le Site Derrière le Site Web', text: 'Regardez une courte visite de notre environnement de production. Pour voir en direct les équipements et capacités actuels, demandez une visioconférence programmée avec notre équipe.', fallback: 'Votre navigateur ne prend pas en charge la vidéo intégrée.', label: 'Visite de l’Usine', meta: 'Environnement de production réel · Guangzhou' },
    gallery: { kicker: 'Au Cœur du Site', title: 'Une Vision Concrète de Notre Façon de Travailler', text: 'Photographies réelles de nos espaces de bureaux, production, remplissage, contrôle, échantillonnage et stockage.', items: gallery([
      { alt: 'Équipements en acier inoxydable pour la composition des parfums dans l’atelier de production', title: 'Atelier de Composition', text: 'Équipements de préparation en acier inoxydable' },
      { alt: 'Équipements de remplissage des parfums et d’assemblage des composants', title: 'Équipements de Remplissage', text: 'Remplissage des produits et manipulation des composants' },
      { alt: 'Équipe de production effectuant le contrôle du packaging et de la qualité', title: 'Contrôle Qualité', text: 'Contrôles en cours de production et marquage' },
      { alt: 'Équipe de l’usine réalisant l’assemblage du packaging des parfums', title: 'Assemblage du Packaging', text: 'Contrôle manuel et emballage secondaire' },
      { alt: 'Grandes cuves de traitement en acier inoxydable dans un atelier contrôlé', title: 'Cuves de Traitement', text: 'Préparation contrôlée des lots' },
      { alt: 'Équipe projets et support commercial de {brand} au travail', title: 'Support Projets', text: 'Devis, échantillonnage et coordination des commandes' },
      { alt: 'Espace de présentation des échantillons de parfums et de packagings', title: 'Showroom Échantillons', text: 'Bibliothèque de référence de flacons et de produits' },
      { alt: 'Entrepôt de préparation des matériaux de packaging et des produits finis', title: 'Stockage et Préparation', text: 'Matériaux de packaging et préparation des expéditions' }
    ]) },
    workflow: { kicker: 'Flux de Production', title: 'Des Étapes Définies, des Responsabilités Visibles', text: 'Les équipements automatisés sont associés au contrôle manuel et à l’emballage secondaire, offrant à chaque projet des points d’approbation et de contrôle clairement établis.', items: [['Préparation des Matières', 'La formule, l’alcool et les composants approuvés sont préparés conformément aux spécifications du projet.'], ['Composition', 'Les lots de parfum sont mélangés dans des équipements de traitement en acier inoxydable.'], ['Macération et Filtration', 'Le lot est conditionné et filtré conformément au plan de production.'], ['Remplissage et Sertissage', 'Les flacons passent par les opérations de remplissage, de pose de la pompe et de fermeture.'], ['Contrôle et Emballage', 'Les produits finis font l’objet de contrôles visuels, de marquage et d’assemblage.'], ['Préparation de l’Expédition', 'Les marchandises sont emballées et préparées pour le mode de transport confirmé.']] },
    certificates: { kicker: 'Certifications et Licences', title: 'Documents Disponibles pour la Vérification par l’Acheteur', intro: 'Afin d’empêcher toute réutilisation non autorisée, les aperçus ci-dessous sont volontairement floutés et en basse résolution. Les copies intégrales sont fournies sur demande aux acheteurs qualifiés.', protected: 'Aperçu Protégé', request: 'Copie Intégrale sur Demande', cards: [['SGS · Certification du Système', 'ISO 22716', 'Bonnes Pratiques de Fabrication des cosmétiques. Période actuelle du certificat indiquée dans notre copie de vérification : {{config.certificates.iso22716.validityDisplay}}.', 'iso-22716-preview.webp', 'Aperçu protégé et flouté du certificat ISO 22716', 480, 679], ['SGS · Évaluation GMP', 'Conformité aux GMP Cosmétiques', 'Évaluation auditée par SGS selon les directives GMP cosmétiques de la CFSAN de la FDA américaine. Elle n’est pas présentée comme une approbation de produit par la FDA.', 'gmp-preview.webp', 'Aperçu protégé et flouté du document d’évaluation GMP cosmétique', 480, 679], ['Administration des Produits Médicaux du Guangdong', 'Licence de Fabrication de Cosmétiques', 'Licence de fabrication délivrée par l’autorité provinciale. La validité actuelle indiquée dans notre copie de vérification court jusqu’au {{config.certificates.manufacturingLicense.validThroughDisplay}}.', 'production-license-preview.webp', 'Aperçu protégé et flouté de la licence de fabrication de cosmétiques', 560, 396]], ctaTitle: 'Besoin de Documents pour Homologuer le Fournisseur ?', ctaText: 'Envoyez le nom de votre entreprise, le marché de destination et la catégorie de produit prévue. Notre équipe vous fournira les documents intégraux pertinents à des fins de vérification.', cta: 'Demander les Certificats Intégraux' }
  }
};
