const commonProducts = [
  ['Fine Fragrance', 'Fine Fragrance'], ['Body or Hair Mist', 'Body or Hair Mist'], ['Home Fragrance', 'Home Fragrance'], ['Packaging Only', 'Packaging Only'], ['Not Yet Decided', 'Not Yet Decided']
];

module.exports = {
  en: {
    hero: { eyebrow: '{brand} Project Desk', title: 'Talk to Our Perfume Manufacturing Team', text: 'Share your product type, estimated quantity and customization requirements. We will review the project and recommend the appropriate manufacturing route and sample option.', primary: 'Start Project Inquiry', secondary: 'Request Free Samples', proof: ['{{site.manufacturer.location.city}}', '{{site.contact.timeZone}}', 'Typical private label MOQ: {{fact("privateLabelMoq")}}'] },
    panel: { eyebrow: 'Contact {brand}', title: 'A Direct Line to the Team Coordinating Your Project', text: '{{site.brand.name}} is an international B2B perfume manufacturing program. Our project team coordinates inquiries, quotations, sampling, manufacturing and export preparation through one workflow.', imageTitle: 'Project Coordination Team', imageMeta: 'Quoting · Sampling · Order follow-up', whatsapp: '{brand} WhatsApp', whatsappAction: 'Open WhatsApp conversation →', email: 'Business Email', emailAction: 'Send your project brief →', location: 'Project Desk', locationAction: 'Factory visit details provided by appointment' },
    cards: [
      //{ kind: 'note', title: 'Program and Manufacturing', text: '{{site.brand.name}} serves international B2B fragrance projects.' },
      { kind: 'sample', eyebrow: 'Free Sample Policy', title: 'Samples Are Free—You Only Pay Courier Cost', text: 'A typical evaluation set contains {{site.samples.setDisplay}} fragrance samples and is prepared in {{site.samples.preparationDays.display}}. The courier quote is confirmed before dispatch.', linkPage: 'process', linkHash: '#free-samples', link: 'View Sample Policy' },
      { kind: 'verification', eyebrow: 'Supplier Verification', title: 'Documents Available to Qualified Buyers', text: 'Manufacturing certificates and company verification documents are available on request during supplier evaluation.', linkPage: 'about', linkHash: '#certificates', link: 'View Protected Certificate Previews' },
      { kind: 'note', title: 'Shipping Note for Alcohol-Based Perfume', text: 'Alcohol-based fragrance is handled through suitable specialist channels. Sample and bulk routes are confirmed according to the destination, quantity and delivery requirements.' }
    ],
    form: { eyebrow: 'Project Review', title: 'Tell Us About Your Project', intro: 'Provide the information you already have. The form prepares a structured WhatsApp inquiry; nothing is sent until you choose to continue.', labels: { name: 'Full Name *', company: 'Company Name', email: 'Business Email *', country: 'Destination Country *', product: 'Product Category *', quantity: 'Estimated Order Volume *', services: 'Cooperation Model', packaging: 'Packaging Status', launch: 'Target Launch Date', details: 'Project Requirements' }, select: 'Select', products: commonProducts, quantities: [['low', 'Low quantity — request review'], ['private', 'Private label range'], ['custom', 'Custom project range'], ['3,000 - 5,000 pcs', '3,000–5,000 pcs'], ['5,000 - 10,000 pcs', '5,000–10,000 pcs'], ['10,000+ pcs', '10,000+ pcs'], ['Not Yet Decided', 'Not Yet Decided']], services: [['Private Label', 'Private Label'], ['Custom Fragrance / ODM', 'Custom Fragrance / ODM'], ['OEM / Contract Processing', 'OEM / Contract Processing'], ['Packaging Support', 'Packaging Support'], ['Free Fragrance Sample Request', 'Free Sample Request']], packaging: [['Not Specified', 'Select status'], ['Need Factory Recommendation', 'Need factory recommendation'], ['Components Already Selected', 'Components already selected'], ['Customer-supplied Components', 'Customer-supplied components'], ['Packaging Only Project', 'Packaging-only project']], launchPlaceholder: 'Month / Year', detailsPlaceholder: 'Scent direction, bottle or packaging preferences, supplied materials, reference samples and other requirements', submit: 'Prepare WhatsApp Inquiry', note: 'Your details are used only to prepare and respond to this business inquiry. Nothing is sent until you continue to WhatsApp. Files and reference images can be attached in WhatsApp after opening the conversation.' }
  },
  'zh-CN': {
    hero: { eyebrow: '{brand} 项目团队', title: '与香水项目团队沟通', text: '提供产品类型、预计数量和定制需求，我们将评估合适的合作路径与样品方案。', primary: '提交项目需求', secondary: '申请基础样品', proof: ['{{site.manufacturer.location.city}}', '{{site.contact.timeZone}}', '私人标签典型起订量：{{fact("privateLabelMoq")}}'] },
    panel: { eyebrow: '联系 {brand}', title: '直接联系负责项目协调的团队', text: '{{site.brand.name}} 是国际 B2B 香水制造项目，项目团队通过统一流程协调询盘、报价、打样、生产和出口准备。', imageTitle: '项目协调团队', imageMeta: '报价 · 打样 · 订单跟进', whatsapp: 'WhatsApp', whatsappAction: '打开 WhatsApp →', email: '业务邮箱', emailAction: '发送项目资料 →', location: '项目团队', locationAction: '工厂参观信息需预约确认' },
    cards: [
      //{ kind: 'note', title: '项目与生产', text: '{{site.brand.name}} 服务于国际 B2B 香水项目。' },
      { kind: 'sample', eyebrow: '免费样品政策', title: '样品免费，仅需承担快递费用', text: '典型评香套装包含 {{site.samples.setDisplay}} 香型样品，通常在 {{site.samples.preparationDays.display}} 内准备。快递报价会在寄出前确认。', linkPage: 'process', linkHash: '#free-samples', link: '查看样品政策' },
      { kind: 'verification', eyebrow: '供应商核验', title: '合格采购方可申请核验文件', text: '供应商审核期间可申请生产证书和公司核验文件。', linkPage: 'about', linkHash: '#certificates', link: '查看受保护的证书预览' },
      { kind: 'note', title: '含酒精香水运输说明', text: '含酒精香氛需通过适合的专业渠道运输。样品和大货路线会根据目的地、数量和交付要求确认。' }
    ],
    form: { eyebrow: '项目评估', title: '告诉我们您的项目需求', intro: '请提供您已经掌握的信息。表单会整理一条 WhatsApp 询盘消息；选择继续之前不会发送任何内容。', labels: { name: '姓名 *', company: '公司名称', email: '业务邮箱 *', country: '目标国家或地区 *', product: '产品类型 *', quantity: '预计数量 *', services: '合作方式', packaging: '包装状态', launch: '计划上市时间', details: '项目要求' }, select: '请选择', products: [['Fine Fragrance', '精品香水'], ['Body or Hair Mist', '身体或发用香氛'], ['Home Fragrance', '家居香氛'], ['Packaging Only', '仅包装'], ['Not Yet Decided', '尚未确定']], quantities: [['low', '低数量——申请个案评估'], ['private', '私人标签数量范围'], ['custom', '定制项目数量范围'], ['3,000 - 5,000 pcs', '3,000–5,000 件'], ['5,000 - 10,000 pcs', '5,000–10,000 件'], ['10,000+ pcs', '10,000 件以上'], ['Not Yet Decided', '尚未确定']], services: [['Private Label', '私人标签'], ['Custom Fragrance / ODM', '定制香型 / ODM'], ['OEM / Contract Processing', 'OEM / 委托加工'], ['Packaging Support', '包装支持'], ['Free Fragrance Sample Request', '申请免费香型样品']], packaging: [['Not Specified', '请选择状态'], ['Need Factory Recommendation', '需要工厂推荐'], ['Components Already Selected', '已选择包装组件'], ['Customer-supplied Components', '客户提供组件'], ['Packaging Only Project', '仅包装项目']], launchPlaceholder: '月份 / 年份', detailsPlaceholder: '香型方向、瓶器或包装偏好、客供材料、参考样品和其他要求', submit: '生成 WhatsApp 询盘', note: '您的资料仅用于整理和回复本次业务询盘。继续到 WhatsApp 前不会发送任何内容；打开对话后可以附加文件和参考图片。' }
  },
  es: {
    hero: { eyebrow: 'Mesa de Proyectos de {brand}', title: 'Hable con Nuestro Equipo de Fabricación de Perfumes', text: 'Indíquenos el tipo de producto, la cantidad estimada y los requisitos de personalización. Revisaremos el proyecto y recomendaremos la modalidad de fabricación y la opción de muestras más adecuadas.', primary: 'Iniciar Consulta de Proyecto', secondary: 'Solicitar Muestras Gratuitas', proof: ['{{site.manufacturer.location.city}}', '{{site.contact.timeZone}}', 'MOQ habitual para marca privada: {{fact("privateLabelMoq")}}'] },
    panel: { eyebrow: 'Contactar con {brand}', title: 'Contacto Directo con el Equipo que Coordina su Proyecto', text: '{{site.brand.name}} es un programa internacional B2B de fabricación de perfumes. Nuestro equipo coordina consultas, cotizaciones, muestreo, fabricación y preparación para la exportación mediante un único flujo de trabajo.', imageTitle: 'Equipo de Coordinación de Proyectos', imageMeta: 'Cotización · Muestreo · Seguimiento de pedidos', whatsapp: 'WhatsApp de {brand}', whatsappAction: 'Abrir conversación en WhatsApp →', email: 'Correo Comercial', emailAction: 'Enviar la información de su proyecto →', location: 'Mesa de Proyectos', locationAction: 'Detalles de la visita a fábrica disponibles con cita previa' },
    cards: [
      //{ kind: 'note', title: 'Programa y Fabricación', text: '{{site.brand.name}} atiende proyectos internacionales B2B de perfumería. ' },
      { kind: 'sample', eyebrow: 'Política de Muestras Gratuitas', title: 'Las Muestras Son Gratuitas; Solo Paga el Envío', text: 'Un set de evaluación habitual contiene {{site.samples.setDisplay}} muestras de fragancias y se prepara en {{site.samples.preparationDays.display}}. La cotización del envío se confirma antes del despacho.', linkPage: 'process', linkHash: '#free-samples', link: 'Ver Política de Muestras' },
      { kind: 'verification', eyebrow: 'Verificación del Proveedor', title: 'Documentos Disponibles para Compradores Cualificados', text: 'Los certificados de fabricación y documentos de verificación de la empresa están disponibles previa solicitud durante la evaluación del proveedor.', linkPage: 'about', linkHash: '#certificates', link: 'Ver Vistas Previas Protegidas de Certificados' },
      { kind: 'note', title: 'Nota de Envío para Perfumes con Alcohol', text: 'Las fragancias con alcohol se transportan mediante canales especializados adecuados. Las rutas para muestras y pedidos a granel se confirman según el destino, la cantidad y los requisitos de entrega.' }
    ],
    form: { eyebrow: 'Evaluación del Proyecto', title: 'Háblenos de su Proyecto', intro: 'Facilite la información que ya tenga. El formulario prepara una consulta estructurada para WhatsApp; no se envía nada hasta que decida continuar.', labels: { name: 'Nombre Completo *', company: 'Nombre de la Empresa', email: 'Correo Comercial *', country: 'País de Destino *', product: 'Categoría de Producto *', quantity: 'Volumen Estimado del Pedido *', services: 'Modalidad de Colaboración', packaging: 'Estado del Envase', launch: 'Fecha Prevista de Lanzamiento', details: 'Requisitos del Proyecto' }, select: 'Seleccionar', products: [['Fine Fragrance', 'Perfumería fina'], ['Body or Hair Mist', 'Bruma corporal o capilar'], ['Home Fragrance', 'Fragancia para el hogar'], ['Packaging Only', 'Solo envases'], ['Not Yet Decided', 'Aún no decidido']], quantities: [['low', 'Cantidad baja — solicitar evaluación'], ['private', 'Rango de marca privada'], ['custom', 'Rango de proyecto personalizado'], ['3,000 - 5,000 pcs', '3,000–5,000 unidades'], ['5,000 - 10,000 pcs', '5,000–10,000 unidades'], ['10,000+ pcs', 'Más de 10,000 unidades'], ['Not Yet Decided', 'Aún no decidido']], services: [['Private Label', 'Marca privada'], ['Custom Fragrance / ODM', 'Fragancia personalizada / ODM'], ['OEM / Contract Processing', 'OEM / Fabricación por contrato'], ['Packaging Support', 'Asistencia con envases'], ['Free Fragrance Sample Request', 'Solicitud de muestras gratuitas']], packaging: [['Not Specified', 'Seleccionar estado'], ['Need Factory Recommendation', 'Necesita recomendación de la fábrica'], ['Components Already Selected', 'Componentes ya seleccionados'], ['Customer-supplied Components', 'Componentes suministrados por el cliente'], ['Packaging Only Project', 'Proyecto solo de envases']], launchPlaceholder: 'Mes / Año', detailsPlaceholder: 'Orientación olfativa, preferencias de frasco o envase, materiales suministrados, muestras de referencia y otros requisitos', submit: 'Preparar Consulta por WhatsApp', note: 'Sus datos se utilizan únicamente para preparar y responder a esta consulta comercial. No se envía nada hasta que continúe en WhatsApp. Podrá adjuntar archivos e imágenes de referencia en WhatsApp después de abrir la conversación.' }
  },
  ar: {
    hero: { eyebrow: 'مكتب مشاريع {brand}', title: 'تواصل مع فريق تصنيع العطور لدينا', text: 'شاركنا نوع المنتج والكمية التقديرية ومتطلبات التخصيص. سنراجع المشروع ونوصي بمسار التصنيع وخيار العينات الأنسب.', primary: 'بدء استفسار المشروع', secondary: 'طلب عينات مجانية', proof: ['{{site.manufacturer.location.city}}', '{{site.contact.timeZone}}', 'الحد الأدنى المعتاد لطلب العلامة الخاصة: {{fact("privateLabelMoq")}}'] },
    panel: { eyebrow: 'تواصل مع {brand}', title: 'خط مباشر مع الفريق المنسق لمشروعك', text: '{{site.brand.name}} برنامج دولي B2B لتصنيع العطور. ينسق فريق المشاريع الاستفسارات وعروض الأسعار والعينات والتصنيع والتحضير للتصدير ضمن سير عمل موحد.', imageTitle: 'فريق تنسيق المشاريع', imageMeta: 'عروض الأسعار · العينات · متابعة الطلبات', whatsapp: 'واتساب {brand}', whatsappAction: 'فتح محادثة واتساب ←', email: 'البريد الإلكتروني للأعمال', emailAction: 'إرسال موجز مشروعك ←', location: 'مكتب المشاريع', locationAction: 'تتوفر تفاصيل زيارة المصنع بموعد مسبق' },
    cards: [
      // { kind: 'note', title: 'البرنامج والتصنيع', text: 'تخدم {{site.brand.name}} مشاريع العطور الدولية بنظام B2B. ' },
      { kind: 'sample', eyebrow: 'سياسة العينات المجانية', title: 'العينات مجانية — تدفع تكلفة الشحن فقط', text: 'تتضمن مجموعة التقييم المعتادة {{site.samples.setDisplay}} عينة عطرية، وتُجهز خلال {{site.samples.preparationDays.display}}. يُؤكد عرض تكلفة الشحن قبل الإرسال.', linkPage: 'process', linkHash: '#free-samples', link: 'عرض سياسة العينات' },
      { kind: 'verification', eyebrow: 'التحقق من المورد', title: 'مستندات متاحة للمشترين المؤهلين', text: 'تتوفر شهادات التصنيع ومستندات التحقق من الشركة عند الطلب أثناء تقييم المورد.', linkPage: 'about', linkHash: '#certificates', link: 'عرض معاينات الشهادات المحمية' },
      { kind: 'note', title: 'ملاحظة شحن العطور المحتوية على الكحول', text: 'تُنقل العطور المحتوية على الكحول عبر قنوات متخصصة مناسبة. وتُحدد مسارات العينات والكميات التجارية وفق الوجهة والكمية ومتطلبات التسليم.' }
    ],
    form: { eyebrow: 'مراجعة المشروع', title: 'أخبرنا عن مشروعك', intro: 'قدم المعلومات المتاحة لديك. يُعد النموذج استفسارًا منظمًا عبر واتساب؛ ولن يُرسل أي شيء حتى تختار المتابعة.', labels: { name: 'الاسم الكامل *', company: 'اسم الشركة', email: 'البريد الإلكتروني للأعمال *', country: 'بلد الوجهة *', product: 'فئة المنتج *', quantity: 'حجم الطلب التقديري *', services: 'نموذج التعاون', packaging: 'حالة العبوة', launch: 'تاريخ الإطلاق المستهدف', details: 'متطلبات المشروع' }, select: 'اختر', products: [['Fine Fragrance', 'عطر فاخر'], ['Body or Hair Mist', 'رذاذ للجسم أو الشعر'], ['Home Fragrance', 'عطر منزلي'], ['Packaging Only', 'العبوات فقط'], ['Not Yet Decided', 'لم يُحدد بعد']], quantities: [['low', 'كمية منخفضة — طلب مراجعة'], ['private', 'نطاق العلامة الخاصة'], ['custom', 'نطاق المشروع المخصص'], ['3,000 - 5,000 pcs', '3,000–5,000 قطعة'], ['5,000 - 10,000 pcs', '5,000–10,000 قطعة'], ['10,000+ pcs', 'أكثر من 10,000 قطعة'], ['Not Yet Decided', 'لم يُحدد بعد']], services: [['Private Label', 'علامة خاصة'], ['Custom Fragrance / ODM', 'عطر مخصص / ODM'], ['OEM / Contract Processing', 'OEM / تصنيع تعاقدي'], ['Packaging Support', 'دعم العبوات'], ['Free Fragrance Sample Request', 'طلب عينات عطرية مجانية']], packaging: [['Not Specified', 'اختر الحالة'], ['Need Factory Recommendation', 'تحتاج إلى توصية المصنع'], ['Components Already Selected', 'تم اختيار المكونات'], ['Customer-supplied Components', 'مكونات يقدمها العميل'], ['Packaging Only Project', 'مشروع عبوات فقط']], launchPlaceholder: 'الشهر / السنة', detailsPlaceholder: 'التوجه العطري، وتفضيلات الزجاجة أو العبوة، والمواد المقدمة، والعينات المرجعية، والمتطلبات الأخرى', submit: 'إعداد استفسار واتساب', note: 'تُستخدم بياناتك فقط لإعداد هذا الاستفسار التجاري والرد عليه. لا يُرسل أي شيء حتى تتابع إلى واتساب. ويمكن إرفاق الملفات والصور المرجعية في واتساب بعد فتح المحادثة.' }
  },
  fr: {
    hero: { eyebrow: 'Bureau Projets {brand}', title: 'Échangez avec Notre Équipe de Fabrication de Parfums', text: 'Indiquez-nous le type de produit, la quantité estimée et vos exigences de personnalisation. Nous étudierons le projet et recommanderons le parcours de fabrication et la formule d’échantillonnage adaptés.', primary: 'Démarrer une Demande de Projet', secondary: 'Demander des Échantillons Gratuits', proof: ['{{site.manufacturer.location.city}}', '{{site.contact.timeZone}}', 'MOQ habituel en marque blanche : {{fact("privateLabelMoq")}}'] },
    panel: { eyebrow: 'Contacter {brand}', title: 'Un Contact Direct avec l’Équipe qui Coordonne Votre Projet', text: '{{site.brand.name}} est un programme international B2B de fabrication de parfums. Notre équipe projets coordonne les demandes, devis, échantillons, fabrication et préparation à l’exportation dans un flux de travail unique.', imageTitle: 'Équipe de Coordination de Projets', imageMeta: 'Devis · Échantillonnage · Suivi des commandes', whatsapp: 'WhatsApp {brand}', whatsappAction: 'Ouvrir la conversation WhatsApp →', email: 'E-mail Professionnel', emailAction: 'Envoyer votre cahier des charges →', location: 'Bureau Projets', locationAction: 'Détails des visites d’usine communiqués sur rendez-vous' },
    cards: [
      //{ kind: 'note', title: 'Programme et Fabrication', text: '{{site.brand.name}} accompagne des projets internationaux B2B de parfumerie. ' },
      { kind: 'sample', eyebrow: 'Politique d’Échantillons Gratuits', title: 'Les Échantillons Sont Gratuits — Seuls les Frais de Transport Sont à Votre Charge', text: 'Un coffret d’évaluation standard contient {{site.samples.setDisplay}} échantillons de parfums et est préparé sous {{site.samples.preparationDays.display}}. Le devis de transport est confirmé avant expédition.', linkPage: 'process', linkHash: '#free-samples', link: 'Voir la Politique d’Échantillons' },
      { kind: 'verification', eyebrow: 'Vérification du Fournisseur', title: 'Documents Disponibles pour les Acheteurs Qualifiés', text: 'Les certificats de fabrication et documents de vérification de l’entreprise sont disponibles sur demande lors de l’évaluation du fournisseur.', linkPage: 'about', linkHash: '#certificates', link: 'Voir les Aperçus Protégés des Certificats' },
      { kind: 'note', title: 'Note d’Expédition pour les Parfums Alcooliques', text: 'Les parfums à base d’alcool sont acheminés par des filières spécialisées adaptées. Les solutions pour les échantillons et les commandes en volume sont confirmées selon la destination, la quantité et les exigences de livraison.' }
    ],
    form: { eyebrow: 'Étude du Projet', title: 'Parlez-Nous de Votre Projet', intro: 'Renseignez les informations dont vous disposez déjà. Le formulaire prépare une demande structurée sur WhatsApp ; rien n’est envoyé avant que vous choisissiez de continuer.', labels: { name: 'Nom Complet *', company: 'Nom de l’Entreprise', email: 'E-mail Professionnel *', country: 'Pays de Destination *', product: 'Catégorie de Produit *', quantity: 'Volume de Commande Estimé *', services: 'Modèle de Collaboration', packaging: 'État du Packaging', launch: 'Date de Lancement Cible', details: 'Exigences du Projet' }, select: 'Sélectionner', products: [['Fine Fragrance', 'Parfum fin'], ['Body or Hair Mist', 'Brume corporelle ou capillaire'], ['Home Fragrance', 'Parfum d’intérieur'], ['Packaging Only', 'Packaging uniquement'], ['Not Yet Decided', 'Pas encore décidé']], quantities: [['low', 'Faible quantité — demander une étude'], ['private', 'Fourchette marque blanche'], ['custom', 'Fourchette projet sur mesure'], ['3,000 - 5,000 pcs', '3,000–5,000 pièces'], ['5,000 - 10,000 pcs', '5,000–10,000 pièces'], ['10,000+ pcs', 'Plus de 10,000 pièces'], ['Not Yet Decided', 'Pas encore décidé']], services: [['Private Label', 'Marque blanche'], ['Custom Fragrance / ODM', 'Parfum sur mesure / ODM'], ['OEM / Contract Processing', 'OEM / Fabrication à façon'], ['Packaging Support', 'Accompagnement packaging'], ['Free Fragrance Sample Request', 'Demande d’échantillons gratuits']], packaging: [['Not Specified', 'Sélectionner le statut'], ['Need Factory Recommendation', 'Recommandation de l’usine nécessaire'], ['Components Already Selected', 'Composants déjà sélectionnés'], ['Customer-supplied Components', 'Composants fournis par le client'], ['Packaging Only Project', 'Projet de packaging uniquement']], launchPlaceholder: 'Mois / Année', detailsPlaceholder: 'Orientation olfactive, préférences de flacon ou de packaging, matières fournies, échantillons de référence et autres exigences', submit: 'Préparer la Demande WhatsApp', note: 'Vos coordonnées servent uniquement à préparer cette demande commerciale et à y répondre. Rien n’est envoyé avant votre passage sur WhatsApp. Vous pourrez joindre des fichiers et images de référence dans WhatsApp après l’ouverture de la conversation.' }
  }
};
