const commonProducts = [
  ['Fine Fragrance','Fine Fragrance'],['Body or Hair Mist','Body or Hair Mist'],['Home Fragrance','Home Fragrance'],['Packaging Only','Packaging Only'],['Not Yet Decided','Not Yet Decided']
];

module.exports = {
  en: {
    hero:{eyebrow:'{brand} Project Desk',title:'Talk to Our Perfume Manufacturing Team',text:'Share your product type, estimated quantity and customization requirements. We will review the project and recommend the appropriate manufacturing route and sample option.',primary:'Start Project Inquiry',secondary:'Request Free Samples',proof:['{{site.manufacturer.location.city}}','{{site.contact.timeZone}}','Typical private label MOQ: {{fact("privateLabelMoq")}}']},
    panel:{eyebrow:'Contact {brand}',title:'A Direct Line to the Team Coordinating Your Project',text:'{{site.brand.legalEntity.en}} operates the {{site.brand.name}} brand and coordinates international inquiries, quotations and sales communication. Confirmed manufacturing is carried out by {{site.manufacturer.legalName}}.',imageTitle:'Project Coordination Team',imageMeta:'Quoting · Sampling · Order follow-up',whatsapp:'{brand} WhatsApp',whatsappAction:'Open WhatsApp conversation →',email:'Business Email',emailAction:'Send your project brief →',location:'Project Desk',locationAction:'Factory visit details provided by appointment'},
    cards:[
      {kind:'note',title:'Brand, Sales and Manufacturing',text:'{{site.brand.name}} is the customer-facing brand of {{site.brand.legalEntity.en}}. Production is completed by the Guangzhou manufacturing entity shown on our Factory & Certificates page.'},
      {kind:'sample',eyebrow:'Free Sample Policy',title:'Samples Are Free—You Only Pay Courier Cost',text:'A typical evaluation set contains {{site.samples.setDisplay}} fragrance samples and is prepared in {{site.samples.preparationDays.display}}. The courier quote is confirmed before dispatch.',linkPage:'process',linkHash:'#free-samples',link:'View Sample Policy'},
      {kind:'verification',eyebrow:'Supplier Verification',title:'Documents Available to Qualified Buyers',text:'Manufacturing certificates and company verification documents are available on request during supplier evaluation.',linkPage:'about',linkHash:'#certificates',link:'View Protected Certificate Previews'},
      {kind:'note',title:'Shipping Note for Alcohol-Based Perfume',text:'Alcohol-based fragrance is handled through suitable specialist channels. Sample and bulk routes are confirmed according to the destination, quantity and delivery requirements.'}
    ],
    form:{eyebrow:'Project Review',title:'Tell Us About Your Project',intro:'Provide the information you already have. The form prepares a structured WhatsApp inquiry; nothing is sent until you choose to continue.',labels:{name:'Full Name *',company:'Company Name',email:'Business Email *',country:'Destination Country *',product:'Product Category *',quantity:'Estimated Order Volume *',services:'Cooperation Model',packaging:'Packaging Status',launch:'Target Launch Date',details:'Project Requirements'},select:'Select',products:commonProducts,quantities:[['low','Low quantity — request review'],['private','Private label range'],['custom','Custom project range'],['3,000 - 5,000 pcs','3,000–5,000 pcs'],['5,000 - 10,000 pcs','5,000–10,000 pcs'],['10,000+ pcs','10,000+ pcs'],['Not Yet Decided','Not Yet Decided']],services:[['Private Label','Private Label'],['Custom Fragrance / ODM','Custom Fragrance / ODM'],['OEM / Contract Processing','OEM / Contract Processing'],['Packaging Support','Packaging Support'],['Free Fragrance Sample Request','Free Sample Request']],packaging:[['Not Specified','Select status'],['Need Factory Recommendation','Need factory recommendation'],['Components Already Selected','Components already selected'],['Customer-supplied Components','Customer-supplied components'],['Packaging Only Project','Packaging-only project']],launchPlaceholder:'Month / Year',detailsPlaceholder:'Scent direction, bottle or packaging preferences, supplied materials, reference samples and other requirements',submit:'Prepare WhatsApp Inquiry',note:'Your details are used only to prepare and respond to this business inquiry. Nothing is sent until you continue to WhatsApp. Files and reference images can be attached in WhatsApp after opening the conversation.'}
  },
  'zh-CN': {
    hero:{eyebrow:'{brand} 项目团队',title:'与香水项目团队沟通',text:'提供产品类型、预计数量和定制需求，我们将评估合适的合作路径与样品方案。',primary:'提交项目需求',secondary:'申请基础样品',proof:['{{site.manufacturer.location.city}}','{{site.contact.timeZone}}','私人标签典型起订量：{{fact("privateLabelMoq")}}']},
    panel:{eyebrow:'联系 {brand}',title:'直接联系负责项目协调的团队',text:'{{site.brand.legalEntity.zh}}负责品牌、国际询盘、报价与销售沟通；确认的生产由 {{site.manufacturer.legalName}}完成。',imageTitle:'项目协调团队',imageMeta:'报价 · 打样 · 订单跟进',whatsapp:'WhatsApp',whatsappAction:'打开 WhatsApp →',email:'业务邮箱',emailAction:'发送项目资料 →',location:'项目团队',locationAction:'工厂参观信息需预约确认'},
    cards:[{kind:'sample',eyebrow:'样品政策',title:'基础香型样品免费',text:'典型套装为 {{fact("sampleSet")}}，客户承担确认后的实际快递费用。',linkPage:'process',linkHash:'#free-samples',link:'查看样品政策'},{kind:'verification',eyebrow:'供应商核验',title:'合格采购方可申请核验文件',text:'供应商审核期间可申请生产证书和公司核验文件。',linkPage:'about',linkHash:'#certificates',link:'查看证书预览'}],
    form:{eyebrow:'项目评估',title:'告诉我们您的项目需求',intro:'表单会整理一条 WhatsApp 询盘消息；点击继续之前不会发送任何内容。',labels:{name:'姓名 *',company:'公司名称',email:'业务邮箱 *',country:'目标国家或地区 *',product:'产品类型 *',quantity:'预计数量 *',services:'合作方式',packaging:'包装状态',launch:'计划上市时间',details:'香型、包装、预算或其他要求'},select:'请选择',products:[['Fine Fragrance','精品香水'],['Body or Hair Mist','身体或发用香氛'],['Home Fragrance','家居香氛'],['Packaging Only','仅包装'],['Not Yet Decided','尚未确定']],quantities:[['low','低于标准起订量，申请评估'],['private','私人标签范围'],['custom','定制项目范围'],['3,000 - 5,000 pcs','3,000–5,000 件'],['5,000+ pcs','5,000+ 件']],services:[['Private Label','私人标签'],['ODM Development','ODM'],['OEM Manufacturing','OEM'],['Free Fragrance Sample Request','基础香型样品']],packaging:[['Not Specified','尚未确定'],['Need Factory Sourcing','需要工厂协助采购'],['Have Reference Images','已有参考图片'],['Customer Supplied','客户提供组件']],launchPlaceholder:'月份 / 年份',detailsPlaceholder:'请说明香型、包装、预算或其他要求',submit:'生成 WhatsApp 询盘',note:'您的资料仅用于整理和回复本次业务询盘；继续前不会发送任何内容。'}
  }
};
