const contactForms = require('./contact');

const en = {
  hero:{eyebrow:'Private Label · OEM · ODM',title:'Private Label Perfume Manufacturer in China',text:'Custom fragrance development, bottle sourcing, filling, packaging and dangerous-goods export support—all managed through one manufacturing partner.',proof:['Typical private label MOQ: {{fact("privateLabelMoq")}}','Samples in {{fact("sampleDaysShort")}}','Global DG shipping support'],primary:'Get Factory Quote',secondary:'Request Sample Kit'},
  metricLabels:['Factory Area','Established','Controlled Workshop','Fragrance Formulas'],
  categories:{kicker:'What We Manufacture',title:'Fragrance Products Built for Your Brand',text:'Choose a product direction and tell us your target market, quantity and customization needs. Our team will recommend the right formula, packaging and production route.',items:[
    ['fine-fragrance','fine-fragrance.webp','Unbranded glass perfume bottles for private label fine fragrance manufacturing','EDP · EDT · Extrait','Fine Fragrance','Custom scent development and private label collections for retail fragrance brands.'],
    ['home-fragrance','home-fragrance.webp','Unbranded reed diffuser, room spray and candle for home fragrance manufacturing','Diffusers · Room Sprays · Candles','Home Fragrance','Coordinated scent and packaging systems for home and lifestyle collections.'],
    ['body-fragrance','body-fragrance.webp','Unbranded fine mist spray bottles for body and hair fragrance manufacturing','Body Mist · Hair Mist','Body Fragrance','Fine-mist formats developed for beauty, personal care and lifestyle brands.'],
    ['packaging-solutions','packaging-solutions.webp','Unbranded perfume bottles, pumps, caps and folding cartons for packaging customization','Bottles · Pumps · Caps · Boxes','Packaging Solutions','Stock and customized components coordinated into a production-ready pack.']],link:'Discuss Your Project',question:'Not sure which production route fits your brand?',cta:'Request Product Recommendations'},
  models:{kicker:'Choose Your Production Route',title:'Three Ways to Build Your Fragrance Line',text:'Start with a ready-to-customize collection, develop a product from the ground up, or bring us your existing formula and packaging.',items:[
    {badge:'Fastest Route',title:'Private Label',text:'Choose from existing fragrance directions, stock bottles and proven packaging formats, then customize the decoration for your brand.',specs:[['Typical MOQ','{{fact("privateLabelMoq")}}'],['Sampling','{{fact("sampleDays")}}'],['Best for','Launches and market tests']],link:'Start a Private Label Project'},
    {badge:'Most Flexible',title:'Full-Service ODM',text:'Develop an original scent and a coordinated packaging system with support from creative brief through production documentation.',specs:[['Typical MOQ','{{fact("customMoq")}}'],['Development','Multiple sample rounds'],['Best for','Original branded collections']],link:'Develop an ODM Collection',featured:true},
    {badge:'Factory Partnership',title:'OEM / Contract Filling',text:'Supply your approved formula, packaging or both. We coordinate compounding, filling, crimping, assembly and batch control.',specs:[['Typical Quantity','Project-based'],['Inputs','Your formula or components'],['Best for','Established fragrance brands']],link:'Discuss Contract Production'}]},
  process:{kicker:'From Brief to Shipment',title:'A Clear Path to Finished Product',text:'Each project follows defined approval points so fragrance, packaging, quality and production expectations stay aligned.',items:[['Brief & Positioning','Share your target market, product format, scent direction, quantity and budget.'],['Fragrance Sampling','Review initial scent directions and refine the selected formula through feedback.'],['Packaging Selection','Confirm bottles, pumps, caps, decoration, labels and outer packaging.'],['Testing & Production','Complete compatibility checks, approvals, filling, crimping and final assembly.'],['DG Export & Delivery','Prepare batch and dangerous-goods documents for specialist freight handling.']],cta:'View Full OEM/ODM Process'},
  extended:{
    fragrance:{kicker:'Fragrance Development',title:'Turn a Direction into a Signature Scent',text:'Begin with a reference, an olfactory family or a brand story. Our sampling workflow translates your brief into fragrance directions ready for evaluation.',families:['Floral','Citrus','Woody','Amber','Fruity','Green','Aquatic','Gourmand'],checks:['Three initial fragrance directions for evaluation','EDP, EDT and extrait concentration planning','Formula refinement based on structured feedback'],cta:'Build Your Fragrance Brief'},
    manufacturing:{kicker:'Manufacturing Capability',title:'Built for Consistent, Scalable Production',text:'From trial launches to recurring wholesale orders, production moves through defined preparation, filling and packing stages.',items:['Fragrance compounding and maceration','Chilling and filtration','Automated filling and pump crimping','Labeling, coding and box assembly','Cellophane wrapping and export packing'],cta:'Request Factory Presentation',caption:'Controlled Production Environment',meta:'Compounding · Filling · Assembly'},
    quality:{kicker:'Quality Control',title:'Quality Checks from Formula to Final Pack',text:'Testing plans are matched to the formula, components and destination requirements before mass production approval.',items:[['Raw Material Inspection','Incoming fragrance, alcohol and packaging components are checked against project specifications.'],['Stability Testing','Formula appearance, odor and color are observed under defined storage conditions.'],['Compatibility Testing','Formula interaction with bottles, pumps, seals and decoration is evaluated before approval.'],['Temperature & Light','High, low and light-exposure conditions help identify potential performance changes.'],['Leakage & Spray Checks','Crimping integrity, leakage risk and spray performance are reviewed on finished packs.'],['Batch Documentation','Production and quality records support COA, SDS and shipment documentation where applicable.']]},
    caseStudy:{kicker:'Example Launch Scope',title:'From Creative Brief to a Three-Scent Collection',text:'This representative project shows how a multi-SKU launch can be structured. Final quantities, timing and sampling rounds are confirmed against the selected formula and packaging.',label:'Representative Project Structure',stats:[['3','EDP scent directions'],['5,000','Bottles per scent'],['3','Sampling rounds'],['35 days','Illustrative production window']],checks:['Stock glass bottle with customized decoration','Coordinated caps, labels and rigid cartons','Batch documentation and DG sea-freight preparation'],cta:'Plan a Similar Collection'},
    export:{kicker:'Global Export Support',title:'Prepared for International Fragrance Shipping',text:'Alcohol-based perfume requires specialist handling. We coordinate the product, batch and dangerous-goods documents needed for the selected freight route.',regions:['North America','Europe','Middle East','Southeast Asia','Australia & New Zealand'],items:[['DG Freight Coordination','Specialist sea and air options for Class 3 alcohol-based fragrance shipments.'],['SDS & Batch Files','Formula and batch documentation prepared where applicable for freight and import review.'],['Export Packing','Carton configuration, product protection and shipment marks coordinated for the route.'],['Destination Guidance','Support for label, carton and logistics requirements based on the destination brief.']],note:'Freight availability, DDP service and destination requirements are confirmed individually for each country and shipment.'},
    faq:{kicker:'Before You Inquire',title:'Common Sourcing Questions',text:'A few practical answers to help you prepare quantity, product and packaging information before requesting a quote.',cta:'View All Questions',items:[['What is the typical minimum order quantity?','{{config.policies.moq}}'],['How long does fragrance sampling take?','Initial samples are typically prepared in {{config.samples.preparationDays.display}} after the brief and logistics arrangement are confirmed. Basic evaluation samples are free; the customer pays the actual courier cost.'],['Can the bottle, cap and box be customized?','Yes. Projects can use stock components with custom color, decoration and printed packaging, or develop dedicated components when quantity and tooling budget allow.'],['What documents can be supplied?','Available files may include SDS, COA, batch records and fragrance-related compliance documentation. Exact documents depend on the formula and destination market.'],['What is the typical production lead time?','Lead time is confirmed after formula and packaging approval. Stock-component projects are generally faster; customized glass, caps or rigid boxes require additional procurement time.'],['How are alcohol-based perfumes shipped?','They are handled as Class 3 Dangerous Goods (UN 1266) through specialist freight channels. The route is selected according to quantity, destination and delivery requirements.']]},
    inquiry:{kicker:'Start a Project',title:'Request Pricing & Sample Options',text:'Tell us what you plan to make, where it will be sold and your estimated quantity. The form prepares a structured WhatsApp inquiry for the factory sales team.',expectations:[['Include','Product type, quantity and destination'],['Receive','Suggested route, MOQ and sample options'],['Next step','Click WhatsApp to deliver the prepared inquiry']],email:'Prefer email?',form:contactForms.en.form}
  }
};

const es = {
  hero:{eyebrow:'Marca privada · OEM · ODM',title:'Fabricante de perfumes de marca privada en China',text:'Desarrollo de fragancias a medida, abastecimiento de frascos, llenado, envasado y apoyo para la exportación de mercancías peligrosas, todo gestionado por un único socio fabricante.',proof:['MOQ habitual para marca privada: {{fact("privateLabelMoq")}}','Muestras en {{fact("sampleDaysShort")}}','Apoyo global para envíos de mercancías peligrosas'],primary:'Solicitar cotización de fábrica',secondary:'Solicitar kit de muestras'},
  metricLabels:['Superficie de la fábrica','Año de fundación','Taller controlado','Fórmulas de fragancias'],
  categories:{kicker:'Qué fabricamos',title:'Productos de perfumería creados para su marca',text:'Elija una categoría de producto e indíquenos su mercado objetivo, cantidad y necesidades de personalización. Nuestro equipo le recomendará la fórmula, el envase y la ruta de producción adecuados.',items:[
    ['fine-fragrance','fine-fragrance.webp','Frascos de perfume de vidrio sin marca para fabricación de perfumería fina de marca privada','EDP · EDT · Extrait','Perfumería fina','Desarrollo de aromas a medida y colecciones de marca privada para marcas minoristas de perfumería.'],
    ['home-fragrance','home-fragrance.webp','Difusor de varillas, espray ambiental y vela sin marca para fabricación de fragancias para el hogar','Difusores · Espráis ambientales · Velas','Fragancias para el hogar','Sistemas coordinados de aromas y envases para colecciones de hogar y estilo de vida.'],
    ['body-fragrance','body-fragrance.webp','Frascos pulverizadores de niebla fina sin marca para fabricación de fragancias corporales y capilares','Bruma corporal · Bruma capilar','Fragancias corporales','Formatos de niebla fina desarrollados para marcas de belleza, cuidado personal y estilo de vida.'],
    ['packaging-solutions','packaging-solutions.webp','Frascos de perfume, bombas, tapones y estuches plegables sin marca para personalización de envases','Frascos · Bombas · Tapones · Cajas','Soluciones de envasado','Componentes estándar y personalizados coordinados en un envase listo para producción.']],link:'Hablar sobre su proyecto',question:'¿No sabe qué ruta de producción se adapta a su marca?',cta:'Solicitar recomendaciones de producto'},
  models:{kicker:'Elija su ruta de producción',title:'Tres formas de crear su línea de fragancias',text:'Comience con una colección lista para personalizar, desarrolle un producto desde cero o facilítenos su fórmula y envase existentes.',items:[
    {badge:'Ruta más rápida',title:'Marca privada',text:'Elija entre perfiles olfativos existentes, frascos estándar y formatos de envase probados; después, personalice la decoración para su marca.',specs:[['MOQ habitual','{{fact("privateLabelMoq")}}'],['Muestreo','{{fact("sampleDays")}}'],['Ideal para','Lanzamientos y pruebas de mercado']],link:'Iniciar un proyecto de marca privada'},
    {badge:'Máxima flexibilidad',title:'ODM integral',text:'Desarrolle un aroma original y un sistema de envasado coordinado, con apoyo desde el brief creativo hasta la documentación de producción.',specs:[['MOQ habitual','{{fact("customMoq")}}'],['Desarrollo','Varias rondas de muestras'],['Ideal para','Colecciones de marca originales']],link:'Desarrollar una colección ODM',featured:true},
    {badge:'Colaboración con fábrica',title:'OEM / Llenado por contrato',text:'Suministre su fórmula aprobada, el envase o ambos. Coordinamos la composición, el llenado, el engastado, el montaje y el control de lotes.',specs:[['Cantidad habitual','Según el proyecto'],['Materiales','Su fórmula o sus componentes'],['Ideal para','Marcas de perfumería consolidadas']],link:'Consultar producción por contrato'}]},
  process:{kicker:'Del brief al envío',title:'Una ruta clara hacia el producto terminado',text:'Cada proyecto sigue puntos de aprobación definidos para mantener alineadas las expectativas de fragancia, envase, calidad y producción.',items:[['Brief y posicionamiento','Comparta su mercado objetivo, formato de producto, dirección olfativa, cantidad y presupuesto.'],['Muestreo de fragancias','Evalúe las propuestas olfativas iniciales y perfeccione la fórmula seleccionada mediante sus comentarios.'],['Selección del envase','Confirme frascos, bombas, tapones, decoración, etiquetas y embalaje exterior.'],['Pruebas y producción','Complete las pruebas de compatibilidad, aprobaciones, llenado, engastado y montaje final.'],['Exportación de mercancías peligrosas y entrega','Prepare la documentación del lote y de mercancías peligrosas para su gestión por transportistas especializados.']],cta:'Ver el proceso completo OEM/ODM'},
  extended:{
    fragrance:{kicker:'Desarrollo de fragancias',title:'Convierta una idea en un aroma distintivo',text:'Parta de una referencia, una familia olfativa o la historia de su marca. Nuestro proceso de muestreo traduce su brief en propuestas olfativas listas para evaluar.',families:['Floral','Cítrica','Amaderada','Ambarada','Afrutada','Verde','Acuática','Gourmand'],checks:['Tres propuestas olfativas iniciales para evaluación','Planificación de concentraciones EDP, EDT y extrait','Perfeccionamiento de la fórmula a partir de comentarios estructurados'],cta:'Crear su brief de fragancia'},
    manufacturing:{kicker:'Capacidad de fabricación',title:'Preparados para una producción uniforme y escalable',text:'Desde lanzamientos piloto hasta pedidos mayoristas recurrentes, la producción avanza mediante etapas definidas de preparación, llenado y envasado.',items:['Composición y maceración de la fragancia','Enfriamiento y filtración','Llenado automatizado y engastado de bombas','Etiquetado, codificación y montaje de cajas','Envoltura de celofán y embalaje para exportación'],cta:'Solicitar presentación de la fábrica',caption:'Entorno de producción controlado',meta:'Composición · Llenado · Montaje'},
    quality:{kicker:'Control de calidad',title:'Controles de calidad desde la fórmula hasta el envase final',text:'Los planes de ensayo se adaptan a la fórmula, los componentes y los requisitos del destino antes de aprobar la producción en serie.',items:[['Inspección de materias primas','Las fragancias, el alcohol y los componentes de envasado recibidos se comprueban conforme a las especificaciones del proyecto.'],['Pruebas de estabilidad','Se observan el aspecto, el olor y el color de la fórmula bajo condiciones de almacenamiento definidas.'],['Pruebas de compatibilidad','Antes de la aprobación se evalúa la interacción de la fórmula con frascos, bombas, sellos y decoración.'],['Temperatura y luz','Las condiciones de alta y baja temperatura y de exposición a la luz ayudan a detectar posibles cambios de rendimiento.'],['Controles de fugas y pulverización','En los envases terminados se revisan la integridad del engastado, el riesgo de fugas y el rendimiento de pulverización.'],['Documentación de lotes','Los registros de producción y calidad respaldan la documentación COA, SDS y de envío cuando corresponde.']]},
    caseStudy:{kicker:'Ejemplo de alcance de lanzamiento',title:'Del brief creativo a una colección de tres aromas',text:'Este proyecto representativo muestra cómo puede estructurarse un lanzamiento con múltiples SKU. Las cantidades, los plazos y las rondas de muestras definitivos se confirman según la fórmula y el envase seleccionados.',label:'Estructura representativa del proyecto',stats:[['3','Propuestas de aromas EDP'],['5,000','Frascos por aroma'],['3','Rondas de muestras'],['35 días','Plazo de producción ilustrativo']],checks:['Frasco de vidrio estándar con decoración personalizada','Tapones, etiquetas y cajas rígidas coordinados','Documentación de lotes y preparación para transporte marítimo de mercancías peligrosas'],cta:'Planificar una colección similar'},
    export:{kicker:'Apoyo global a la exportación',title:'Preparados para el envío internacional de fragancias',text:'Los perfumes a base de alcohol requieren una gestión especializada. Coordinamos la documentación del producto, del lote y de mercancías peligrosas necesaria para la ruta de transporte elegida.',regions:['Norteamérica','Europa','Oriente Medio','Sudeste Asiático','Australia y Nueva Zelanda'],items:[['Coordinación de transporte de mercancías peligrosas','Opciones especializadas por mar y aire para envíos de fragancias a base de alcohol de Clase 3.'],['SDS y archivos de lote','Cuando corresponde, se prepara la documentación de fórmula y lote para la revisión de transporte e importación.'],['Embalaje para exportación','La configuración de cajas, la protección del producto y las marcas de envío se coordinan según la ruta.'],['Orientación para el destino','Apoyo con los requisitos de etiquetas, cajas y logística según el brief del destino.']],note:'La disponibilidad de transporte, el servicio DDP y los requisitos del destino se confirman individualmente para cada país y envío.'},
    faq:{kicker:'Antes de consultar',title:'Preguntas habituales de abastecimiento',text:'Algunas respuestas prácticas para ayudarle a preparar la información sobre cantidades, productos y envases antes de solicitar una cotización.',cta:'Ver todas las preguntas',items:[['¿Cuál es la cantidad mínima de pedido habitual?','{{config.policies.moq}}'],['¿Cuánto tarda el muestreo de fragancias?','Las muestras iniciales suelen prepararse en {{config.samples.preparationDays.display}} una vez confirmados el brief y la organización logística. Las muestras básicas de evaluación son gratuitas; el cliente paga el coste real de mensajería.'],['¿Se pueden personalizar el frasco, el tapón y la caja?','Sí. Los proyectos pueden usar componentes estándar con color, decoración y embalaje impreso personalizados, o desarrollar componentes exclusivos cuando la cantidad y el presupuesto de utillaje lo permitan.'],['¿Qué documentos pueden suministrarse?','Los archivos disponibles pueden incluir SDS, COA, registros de lotes y documentación de conformidad relacionada con la fragancia. Los documentos exactos dependen de la fórmula y del mercado de destino.'],['¿Cuál es el plazo de producción habitual?','El plazo se confirma después de aprobar la fórmula y el envase. Los proyectos con componentes estándar suelen ser más rápidos; el vidrio, los tapones o las cajas rígidas personalizados requieren tiempo adicional de aprovisionamiento.'],['¿Cómo se envían los perfumes a base de alcohol?','Se gestionan como mercancías peligrosas de Clase 3 (UN 1266) mediante canales de transporte especializados. La ruta se selecciona según la cantidad, el destino y los requisitos de entrega.']]},
    inquiry:{kicker:'Iniciar un proyecto',title:'Solicitar precios y opciones de muestras',text:'Indíquenos qué desea fabricar, dónde se venderá y la cantidad estimada. El formulario prepara una consulta estructurada por WhatsApp para el equipo comercial de la fábrica.',expectations:[['Incluya','Tipo de producto, cantidad y destino'],['Reciba','Ruta recomendada, MOQ y opciones de muestras'],['Siguiente paso','Pulse WhatsApp para enviar la consulta preparada']],email:'¿Prefiere el correo electrónico?',form:{eyebrow:'Evaluación del proyecto',title:'Cuéntenos su proyecto',intro:'Facilite la información que ya tenga. El formulario prepara una consulta estructurada por WhatsApp; no se envía nada hasta que decida continuar.',labels:{name:'Nombre completo *',company:'Empresa',email:'Correo electrónico profesional *',country:'País de destino *',product:'Categoría de producto *',quantity:'Volumen estimado del pedido *',services:'Modelo de colaboración',packaging:'Estado del envase',launch:'Fecha prevista de lanzamiento',details:'Requisitos del proyecto'},select:'Seleccionar',products:[['Fine Fragrance','Perfumería fina'],['Body or Hair Mist','Bruma corporal o capilar'],['Home Fragrance','Fragancias para el hogar'],['Packaging Only','Solo envases'],['Not Yet Decided','Aún no decidido']],quantities:[['low','Cantidad baja — solicitar evaluación'],['private','Rango de marca privada'],['custom','Rango de proyecto personalizado'],['3,000 - 5,000 pcs','3,000–5,000 unidades'],['5,000 - 10,000 pcs','5,000–10,000 unidades'],['10,000+ pcs','10,000+ unidades'],['Not Yet Decided','Aún no decidido']],services:[['Private Label','Marca privada'],['Custom Fragrance / ODM','Fragancia a medida / ODM'],['OEM / Contract Processing','OEM / Fabricación por contrato'],['Packaging Support','Apoyo de envasado'],['Free Fragrance Sample Request','Solicitud de muestras gratuitas de fragancia']],packaging:[['Not Specified','Seleccionar estado'],['Need Factory Recommendation','Necesito recomendación de la fábrica'],['Components Already Selected','Componentes ya seleccionados'],['Customer-supplied Components','Componentes suministrados por el cliente'],['Packaging Only Project','Proyecto solo de envasado']],launchPlaceholder:'Mes / Año',detailsPlaceholder:'Dirección olfativa, preferencias de frasco o envase, materiales suministrados, muestras de referencia y otros requisitos',submit:'Preparar consulta por WhatsApp',note:'Sus datos se utilizan únicamente para preparar y responder a esta consulta comercial. No se envía nada hasta que continúe a WhatsApp. Después de abrir la conversación podrá adjuntar archivos e imágenes de referencia.'}}
  }
};

const ar = {
  hero:{eyebrow:'علامة خاصة · OEM · ODM',title:'مصنّع عطور بعلامة خاصة في الصين',text:'تطوير عطور مخصصة، وتوريد العبوات، والتعبئة، والتغليف، ودعم تصدير المواد الخطرة، وكل ذلك عبر شريك تصنيع واحد.',proof:['الحد الأدنى المعتاد لطلبات العلامة الخاصة: {{fact("privateLabelMoq")}}','العينات خلال {{fact("sampleDaysShort")}}','دعم عالمي لشحن المواد الخطرة'],primary:'اطلب عرض سعر من المصنع',secondary:'اطلب مجموعة عينات'},
  metricLabels:['مساحة المصنع','سنة التأسيس','ورشة إنتاج خاضعة للرقابة','تركيبات عطرية'],
  categories:{kicker:'ما نصنّعه',title:'منتجات عطرية مصممة لعلامتك التجارية',text:'اختر فئة المنتج وأخبرنا بالسوق المستهدف والكمية ومتطلبات التخصيص. سيوصي فريقنا بالتركيبة والتغليف ومسار الإنتاج الأنسب.',items:[
    ['fine-fragrance','fine-fragrance.webp','زجاجات عطر غير موسومة لتصنيع العطور الراقية بعلامة خاصة','EDP · EDT · Extrait','العطور الراقية','تطوير روائح مخصصة ومجموعات بعلامة خاصة لعلامات العطور المخصصة للبيع بالتجزئة.'],
    ['home-fragrance','home-fragrance.webp','ناشر عطري بعيدان وبخاخ للغرف وشمعة غير موسومة لتصنيع عطور المنزل','ناشرات عطرية · بخاخات غرف · شموع','عطور المنزل','أنظمة متناسقة للرائحة والتغليف لمجموعات المنزل ونمط الحياة.'],
    ['body-fragrance','body-fragrance.webp','عبوات رذاذ ناعم غير موسومة لتصنيع عطور الجسم والشعر','رذاذ جسم · رذاذ شعر','عطور الجسم','صيغ برذاذ ناعم مطورة لعلامات الجمال والعناية الشخصية ونمط الحياة.'],
    ['packaging-solutions','packaging-solutions.webp','زجاجات عطر ومضخات وأغطية وعلب كرتونية قابلة للطي غير موسومة لتخصيص التغليف','زجاجات · مضخات · أغطية · علب','حلول التغليف','تنسيق المكونات الجاهزة والمخصصة في عبوة مكتملة وجاهزة للإنتاج.']],link:'ناقش مشروعك',question:'لست متأكدًا من مسار الإنتاج الأنسب لعلامتك؟',cta:'اطلب توصيات المنتجات'},
  models:{kicker:'اختر مسار الإنتاج',title:'ثلاث طرق لإنشاء خط عطورك',text:'ابدأ بمجموعة جاهزة للتخصيص، أو طوّر منتجًا من الصفر، أو زوّدنا بتركيبتك وتغليفك الحاليين.',items:[
    {badge:'المسار الأسرع',title:'العلامة الخاصة',text:'اختر من توجهات عطرية قائمة وزجاجات جاهزة وصيغ تغليف مجرّبة، ثم خصص الزخرفة لعلامتك التجارية.',specs:[['الحد الأدنى المعتاد للطلب','{{fact("privateLabelMoq")}}'],['إعداد العينات','{{fact("sampleDays")}}'],['الأنسب لـ','الإطلاقات واختبارات السوق']],link:'ابدأ مشروع علامة خاصة'},
    {badge:'الأكثر مرونة',title:'خدمة ODM متكاملة',text:'طوّر رائحة أصلية ونظام تغليف متناسقًا، مع دعم من الموجز الإبداعي حتى وثائق الإنتاج.',specs:[['الحد الأدنى المعتاد للطلب','{{fact("customMoq")}}'],['التطوير','جولات متعددة من العينات'],['الأنسب لـ','المجموعات الأصلية ذات العلامة التجارية']],link:'طوّر مجموعة ODM',featured:true},
    {badge:'شراكة مع المصنع',title:'OEM / تعبئة تعاقدية',text:'زوّدنا بالتركيبة المعتمدة أو التغليف أو كليهما. ننسق الخلط والتعبئة وكبس المضخة والتجميع وضبط الدفعات.',specs:[['الكمية المعتادة','بحسب المشروع'],['المدخلات','تركيبتك أو مكوناتك'],['الأنسب لـ','علامات العطور الراسخة']],link:'ناقش الإنتاج التعاقدي'}]},
  process:{kicker:'من الموجز إلى الشحن',title:'مسار واضح نحو المنتج النهائي',text:'يتبع كل مشروع نقاط اعتماد محددة لضمان توافق توقعات العطر والتغليف والجودة والإنتاج.',items:[['الموجز والتموضع','شارك السوق المستهدف وشكل المنتج والتوجه العطري والكمية والميزانية.'],['عينات العطر','راجع التوجهات العطرية الأولية وحسّن التركيبة المختارة من خلال الملاحظات.'],['اختيار التغليف','اعتمد الزجاجات والمضخات والأغطية والزخرفة والملصقات والتغليف الخارجي.'],['الاختبارات والإنتاج','أكمل اختبارات التوافق والاعتمادات والتعبئة وكبس المضخات والتجميع النهائي.'],['تصدير المواد الخطرة والتسليم','جهّز وثائق الدفعة والمواد الخطرة للمناولة عبر شركات شحن متخصصة.']],cta:'شاهد عملية OEM/ODM كاملة'},
  extended:{
    fragrance:{kicker:'تطوير العطور',title:'حوّل التوجه إلى رائحة مميزة',text:'ابدأ بمرجع أو عائلة عطرية أو قصة علامة تجارية. يحوّل مسار إعداد العينات موجزك إلى توجهات عطرية جاهزة للتقييم.',families:['زهرية','حمضية','خشبية','عنبرية','فاكهية','خضراء','مائية','Gourmand'],checks:['ثلاثة توجهات عطرية أولية للتقييم','تخطيط تركيزات EDP وEDT وextrait','تحسين التركيبة استنادًا إلى ملاحظات منظمة'],cta:'أنشئ موجز عطرك'},
    manufacturing:{kicker:'القدرة التصنيعية',title:'مصمم لإنتاج متسق وقابل للتوسع',text:'من الإطلاقات التجريبية إلى طلبات الجملة المتكررة، يمر الإنتاج بمراحل محددة للتحضير والتعبئة والتغليف.',items:['خلط العطر وتعتيقه','التبريد والترشيح','التعبئة الآلية وكبس المضخات','وضع الملصقات والترميز وتجميع العلب','التغليف بالسيلوفان والتعبئة للتصدير'],cta:'اطلب عرض المصنع',caption:'بيئة إنتاج خاضعة للرقابة',meta:'الخلط · التعبئة · التجميع'},
    quality:{kicker:'مراقبة الجودة',title:'فحوص الجودة من التركيبة إلى العبوة النهائية',text:'تُطابق خطط الاختبار مع التركيبة والمكونات ومتطلبات الوجهة قبل اعتماد الإنتاج الكمي.',items:[['فحص المواد الخام','تُفحص العطور والكحول ومكونات التغليف الواردة وفق مواصفات المشروع.'],['اختبار الثبات','يُراقب مظهر التركيبة ورائحتها ولونها في ظروف تخزين محددة.'],['اختبار التوافق','يُقيّم تفاعل التركيبة مع الزجاجات والمضخات ومواد الإحكام والزخرفة قبل الاعتماد.'],['الحرارة والضوء','تساعد ظروف الحرارة المرتفعة والمنخفضة والتعرض للضوء في تحديد تغيرات الأداء المحتملة.'],['فحوص التسرب والرش','تُراجع سلامة الكبس ومخاطر التسرب وأداء الرش في العبوات النهائية.'],['وثائق الدفعات','تدعم سجلات الإنتاج والجودة وثائق COA وSDS والشحن عند الاقتضاء.']]},
    caseStudy:{kicker:'مثال على نطاق الإطلاق',title:'من الموجز الإبداعي إلى مجموعة من ثلاث روائح',text:'يوضح هذا المشروع التمثيلي كيفية تنظيم إطلاق متعدد SKU. تُعتمد الكميات النهائية والمدة وجولات العينات وفق التركيبة والتغليف المختارين.',label:'هيكل تمثيلي للمشروع',stats:[['3','توجهات عطرية EDP'],['5,000','زجاجة لكل رائحة'],['3','جولات عينات'],['35 يومًا','مدة إنتاج توضيحية']],checks:['زجاجة جاهزة مع زخرفة مخصصة','أغطية وملصقات وعلب صلبة متناسقة','وثائق الدفعات والتحضير للشحن البحري للمواد الخطرة'],cta:'خطط لمجموعة مماثلة'},
    export:{kicker:'دعم التصدير العالمي',title:'جاهزون لشحن العطور دوليًا',text:'تتطلب العطور الكحولية مناولة متخصصة. ننسق وثائق المنتج والدفعة والمواد الخطرة اللازمة لمسار الشحن المختار.',regions:['أمريكا الشمالية','أوروبا','الشرق الأوسط','جنوب شرق آسيا','أستراليا ونيوزيلندا'],items:[['تنسيق شحن المواد الخطرة','خيارات بحرية وجوية متخصصة لشحنات العطور الكحولية من الفئة 3.'],['ملفات SDS والدفعات','تُعد وثائق التركيبة والدفعة عند الاقتضاء لمراجعة الشحن والاستيراد.'],['التعبئة للتصدير','يُنسق تكوين الكراتين وحماية المنتج وعلامات الشحن وفق المسار.'],['إرشادات الوجهة','دعم متطلبات الملصقات والكراتين والخدمات اللوجستية وفق موجز الوجهة.']],note:'يُؤكد توفر الشحن وخدمة DDP ومتطلبات الوجهة بصورة منفصلة لكل بلد وشحنة.'},
    faq:{kicker:'قبل إرسال استفسارك',title:'أسئلة التوريد الشائعة',text:'إجابات عملية تساعدك في إعداد معلومات الكمية والمنتج والتغليف قبل طلب عرض سعر.',cta:'شاهد جميع الأسئلة',items:[['ما الحد الأدنى المعتاد لكمية الطلب؟','{{config.policies.moq}}'],['كم يستغرق إعداد عينات العطر؟','تُجهز العينات الأولية عادةً خلال {{config.samples.preparationDays.display}} بعد اعتماد الموجز والترتيبات اللوجستية. عينات التقييم الأساسية مجانية، ويتحمل العميل تكلفة الشحن الفعلية.'],['هل يمكن تخصيص الزجاجة والغطاء والعلبة؟','نعم. يمكن استخدام مكونات جاهزة مع لون وزخرفة وتغليف مطبوع مخصص، أو تطوير مكونات خاصة عندما تسمح الكمية وميزانية القوالب.'],['ما الوثائق التي يمكن توفيرها؟','قد تشمل الملفات المتاحة SDS وCOA وسجلات الدفعات ووثائق الامتثال المتعلقة بالعطر. تعتمد الوثائق الدقيقة على التركيبة وسوق الوجهة.'],['ما مدة الإنتاج المعتادة؟','تُعتمد المدة بعد الموافقة على التركيبة والتغليف. تكون مشاريع المكونات الجاهزة أسرع عمومًا، بينما يتطلب الزجاج أو الأغطية أو العلب الصلبة المخصصة وقت توريد إضافيًا.'],['كيف تُشحن العطور الكحولية؟','تُعامل بوصفها مواد خطرة من الفئة 3 (UN 1266) عبر قنوات شحن متخصصة. يُختار المسار وفق الكمية والوجهة ومتطلبات التسليم.']]},
    inquiry:{kicker:'ابدأ مشروعًا',title:'اطلب الأسعار وخيارات العينات',text:'أخبرنا بما تخطط لتصنيعه ومكان بيعه والكمية التقديرية. يُعد النموذج استفسار WhatsApp منظمًا لفريق مبيعات المصنع.',expectations:[['أدرج','نوع المنتج والكمية والوجهة'],['ستتلقى','المسار المقترح والحد الأدنى للطلب وخيارات العينات'],['الخطوة التالية','انقر على WhatsApp لإرسال الاستفسار المُعد']],email:'تفضل البريد الإلكتروني؟',form:{eyebrow:'مراجعة المشروع',title:'أخبرنا عن مشروعك',intro:'قدّم المعلومات المتوفرة لديك. يُعد النموذج استفسار WhatsApp منظمًا، ولن يُرسل شيء حتى تختار المتابعة.',labels:{name:'الاسم الكامل *',company:'اسم الشركة',email:'البريد الإلكتروني للعمل *',country:'بلد الوجهة *',product:'فئة المنتج *',quantity:'حجم الطلب التقديري *',services:'نموذج التعاون',packaging:'حالة التغليف',launch:'موعد الإطلاق المستهدف',details:'متطلبات المشروع'},select:'اختر',products:[['Fine Fragrance','عطور راقية'],['Body or Hair Mist','رذاذ للجسم أو الشعر'],['Home Fragrance','عطور منزلية'],['Packaging Only','تغليف فقط'],['Not Yet Decided','لم يُحدد بعد']],quantities:[['low','كمية منخفضة — اطلب المراجعة'],['private','نطاق العلامة الخاصة'],['custom','نطاق المشروع المخصص'],['3,000 - 5,000 pcs','3,000–5,000 قطعة'],['5,000 - 10,000 pcs','5,000–10,000 قطعة'],['10,000+ pcs','10,000+ قطعة'],['Not Yet Decided','لم يُحدد بعد']],services:[['Private Label','علامة خاصة'],['Custom Fragrance / ODM','عطر مخصص / ODM'],['OEM / Contract Processing','OEM / تصنيع تعاقدي'],['Packaging Support','دعم التغليف'],['Free Fragrance Sample Request','طلب عينات عطر مجانية']],packaging:[['Not Specified','اختر الحالة'],['Need Factory Recommendation','أحتاج إلى توصية المصنع'],['Components Already Selected','تم اختيار المكونات'],['Customer-supplied Components','مكونات يقدمها العميل'],['Packaging Only Project','مشروع تغليف فقط']],launchPlaceholder:'الشهر / السنة',detailsPlaceholder:'التوجه العطري، وتفضيلات الزجاجة أو التغليف، والمواد المقدمة، والعينات المرجعية، والمتطلبات الأخرى',submit:'إعداد استفسار WhatsApp',note:'تُستخدم بياناتك فقط لإعداد هذا الاستفسار التجاري والرد عليه. لن يُرسل شيء حتى تنتقل إلى WhatsApp. ويمكن إرفاق الملفات والصور المرجعية بعد فتح المحادثة.'}}
  }
};

const fr = {
  hero:{eyebrow:'Marque blanche · OEM · ODM',title:'Fabricant de parfums en marque blanche en Chine',text:'Développement de fragrances sur mesure, approvisionnement en flacons, remplissage, conditionnement et assistance à l’exportation de marchandises dangereuses, le tout géré par un seul partenaire industriel.',proof:['MOQ habituel en marque blanche : {{fact("privateLabelMoq")}}','Échantillons sous {{fact("sampleDaysShort")}}','Assistance mondiale pour l’expédition de marchandises dangereuses'],primary:'Demander un devis usine',secondary:'Demander un kit d’échantillons'},
  metricLabels:['Surface de l’usine','Année de création','Atelier contrôlé','Formules de fragrances'],
  categories:{kicker:'Nos fabrications',title:'Des produits parfumés conçus pour votre marque',text:'Choisissez une catégorie de produit et indiquez-nous votre marché cible, la quantité et vos besoins de personnalisation. Notre équipe vous recommandera la formule, le conditionnement et le parcours de production adaptés.',items:[
    ['fine-fragrance','fine-fragrance.webp','Flacons de parfum en verre sans marque pour la fabrication de parfumerie fine en marque blanche','EDP · EDT · Extrait','Parfumerie fine','Développement de senteurs sur mesure et collections en marque blanche pour les marques de parfumerie distribuées au détail.'],
    ['home-fragrance','home-fragrance.webp','Diffuseur à bâtonnets, vaporisateur d’ambiance et bougie sans marque pour la fabrication de parfums d’intérieur','Diffuseurs · Sprays d’ambiance · Bougies','Parfums d’intérieur','Systèmes coordonnés de senteurs et de conditionnements pour les collections maison et art de vivre.'],
    ['body-fragrance','body-fragrance.webp','Flacons vaporisateurs à brume fine sans marque pour la fabrication de parfums pour le corps et les cheveux','Brume corps · Brume cheveux','Parfums pour le corps','Formats à brume fine développés pour les marques de beauté, de soins personnels et d’art de vivre.'],
    ['packaging-solutions','packaging-solutions.webp','Flacons de parfum, pompes, capots et étuis pliants sans marque pour la personnalisation du conditionnement','Flacons · Pompes · Capots · Boîtes','Solutions de conditionnement','Composants standard et personnalisés coordonnés dans un emballage prêt pour la production.']],link:'Parler de votre projet',question:'Vous ne savez pas quel parcours de production convient à votre marque ?',cta:'Demander des recommandations de produits'},
  models:{kicker:'Choisissez votre parcours de production',title:'Trois façons de créer votre gamme de parfums',text:'Partez d’une collection prête à personnaliser, développez un produit de A à Z ou confiez-nous votre formule et votre conditionnement existants.',items:[
    {badge:'Parcours le plus rapide',title:'Marque blanche',text:'Choisissez parmi des orientations olfactives existantes, des flacons standard et des formats de conditionnement éprouvés, puis personnalisez le décor aux couleurs de votre marque.',specs:[['MOQ habituel','{{fact("privateLabelMoq")}}'],['Échantillonnage','{{fact("sampleDays")}}'],['Idéal pour','Lancements et tests de marché']],link:'Lancer un projet en marque blanche'},
    {badge:'Flexibilité maximale',title:'ODM clé en main',text:'Développez une senteur originale et un système de conditionnement coordonné, avec un accompagnement du brief créatif jusqu’aux documents de production.',specs:[['MOQ habituel','{{fact("customMoq")}}'],['Développement','Plusieurs séries d’échantillons'],['Idéal pour','Collections de marque originales']],link:'Développer une collection ODM',featured:true},
    {badge:'Partenariat industriel',title:'OEM / Remplissage à façon',text:'Fournissez votre formule approuvée, votre conditionnement ou les deux. Nous coordonnons la composition, le remplissage, le sertissage, l’assemblage et le contrôle des lots.',specs:[['Quantité habituelle','Selon le projet'],['Éléments fournis','Votre formule ou vos composants'],['Idéal pour','Marques de parfumerie établies']],link:'Discuter d’une production à façon'}]},
  process:{kicker:'Du brief à l’expédition',title:'Un parcours clair jusqu’au produit fini',text:'Chaque projet suit des étapes de validation définies afin d’aligner les attentes en matière de fragrance, de conditionnement, de qualité et de production.',items:[['Brief et positionnement','Communiquez votre marché cible, le format du produit, l’orientation olfactive, la quantité et le budget.'],['Échantillonnage des fragrances','Évaluez les premières orientations olfactives et affinez la formule retenue grâce à vos retours.'],['Sélection du conditionnement','Validez les flacons, pompes, capots, décors, étiquettes et emballages extérieurs.'],['Tests et production','Finalisez les tests de compatibilité, les validations, le remplissage, le sertissage et l’assemblage final.'],['Exportation de marchandises dangereuses et livraison','Préparez les documents de lot et de marchandises dangereuses pour une prise en charge par des transporteurs spécialisés.']],cta:'Voir le processus OEM/ODM complet'},
  extended:{
    fragrance:{kicker:'Développement de fragrances',title:'Transformez une orientation en signature olfactive',text:'Partez d’une référence, d’une famille olfactive ou de l’histoire de votre marque. Notre processus d’échantillonnage traduit votre brief en orientations olfactives prêtes à être évaluées.',families:['Florale','Hespéridée','Boisée','Ambrée','Fruitée','Verte','Aquatique','Gourmande'],checks:['Trois orientations olfactives initiales à évaluer','Planification des concentrations EDP, EDT et extrait','Affinement de la formule à partir de retours structurés'],cta:'Créer votre brief olfactif'},
    manufacturing:{kicker:'Capacités de fabrication',title:'Une production régulière et évolutive',text:'Des lancements pilotes aux commandes de gros récurrentes, la production progresse selon des étapes définies de préparation, de remplissage et de conditionnement.',items:['Composition et macération de la fragrance','Refroidissement et filtration','Remplissage automatisé et sertissage des pompes','Étiquetage, codage et montage des boîtes','Cellophanage et emballage pour l’exportation'],cta:'Demander la présentation de l’usine',caption:'Environnement de production contrôlé',meta:'Composition · Remplissage · Assemblage'},
    quality:{kicker:'Contrôle qualité',title:'Des contrôles qualité de la formule au conditionnement final',text:'Les plans d’essai sont adaptés à la formule, aux composants et aux exigences de destination avant l’autorisation de la production en série.',items:[['Contrôle des matières premières','Les fragrances, l’alcool et les composants de conditionnement entrants sont contrôlés selon les spécifications du projet.'],['Tests de stabilité','L’aspect, l’odeur et la couleur de la formule sont observés dans des conditions de stockage définies.'],['Tests de compatibilité','L’interaction de la formule avec les flacons, les pompes, les joints et le décor est évaluée avant validation.'],['Température et lumière','Les conditions de haute et basse température ainsi que l’exposition à la lumière permettent d’identifier d’éventuelles variations de performance.'],['Contrôles d’étanchéité et de pulvérisation','L’intégrité du sertissage, le risque de fuite et la qualité de pulvérisation sont contrôlés sur les produits finis.'],['Documentation des lots','Les dossiers de production et de qualité étayent les documents COA, SDS et d’expédition, le cas échéant.']]},
    caseStudy:{kicker:'Exemple de périmètre de lancement',title:'Du brief créatif à une collection de trois senteurs',text:'Ce projet représentatif montre comment structurer un lancement comprenant plusieurs SKU. Les quantités, les délais et les séries d’échantillons définitifs sont confirmés selon la formule et le conditionnement retenus.',label:'Structure représentative du projet',stats:[['3','Orientations olfactives EDP'],['5,000','Flacons par senteur'],['3','Séries d’échantillons'],['35 jours','Délai de production indicatif']],checks:['Flacon en verre standard avec décor personnalisé','Capots, étiquettes et coffrets rigides coordonnés','Documentation des lots et préparation du fret maritime de marchandises dangereuses'],cta:'Planifier une collection similaire'},
    export:{kicker:'Assistance mondiale à l’exportation',title:'Prêts pour l’expédition internationale de parfums',text:'Les parfums à base d’alcool exigent une manutention spécialisée. Nous coordonnons les documents relatifs au produit, au lot et aux marchandises dangereuses nécessaires pour le mode de transport choisi.',regions:['Amérique du Nord','Europe','Moyen-Orient','Asie du Sud-Est','Australie et Nouvelle-Zélande'],items:[['Coordination du transport de marchandises dangereuses','Solutions maritimes et aériennes spécialisées pour les expéditions de parfums à base d’alcool de classe 3.'],['SDS et dossiers de lot','La documentation de formule et de lot est préparée, le cas échéant, pour l’examen du transporteur et des services d’importation.'],['Emballage pour l’exportation','La configuration des cartons, la protection des produits et les marquages d’expédition sont coordonnés selon l’itinéraire.'],['Conseils pour la destination','Assistance concernant les exigences d’étiquetage, de mise en carton et de logistique selon le brief de destination.']],note:'La disponibilité du transport, le service DDP et les exigences de destination sont confirmés individuellement pour chaque pays et chaque expédition.'},
    faq:{kicker:'Avant votre demande',title:'Questions fréquentes sur l’approvisionnement',text:'Quelques réponses pratiques pour vous aider à préparer les informations sur les quantités, les produits et le conditionnement avant de demander un devis.',cta:'Voir toutes les questions',items:[['Quelle est la quantité minimale de commande habituelle ?','{{config.policies.moq}}'],['Combien de temps faut-il pour préparer les échantillons de fragrance ?','Les premiers échantillons sont généralement préparés sous {{config.samples.preparationDays.display}} après validation du brief et de l’organisation logistique. Les échantillons d’évaluation de base sont gratuits ; le client règle les frais réels de messagerie.'],['Le flacon, le capot et la boîte peuvent-ils être personnalisés ?','Oui. Les projets peuvent utiliser des composants standard avec une couleur, un décor et un emballage imprimé personnalisés, ou développer des composants dédiés lorsque la quantité et le budget d’outillage le permettent.'],['Quels documents peuvent être fournis ?','Les dossiers disponibles peuvent inclure les SDS, COA, dossiers de lot et documents de conformité liés à la fragrance. Les documents précis dépendent de la formule et du marché de destination.'],['Quel est le délai de production habituel ?','Le délai est confirmé après validation de la formule et du conditionnement. Les projets utilisant des composants standard sont généralement plus rapides ; le verre, les capots ou les coffrets rigides personnalisés nécessitent un délai d’approvisionnement supplémentaire.'],['Comment les parfums à base d’alcool sont-ils expédiés ?','Ils sont traités comme des marchandises dangereuses de classe 3 (UN 1266) par des filières de transport spécialisées. Le mode d’acheminement est choisi selon la quantité, la destination et les exigences de livraison.']]},
    inquiry:{kicker:'Lancer un projet',title:'Demander les tarifs et les options d’échantillons',text:'Indiquez-nous ce que vous prévoyez de fabriquer, où le produit sera vendu et la quantité estimée. Le formulaire prépare une demande structurée sur WhatsApp pour l’équipe commerciale de l’usine.',expectations:[['À inclure','Type de produit, quantité et destination'],['Vous recevrez','Parcours recommandé, MOQ et options d’échantillons'],['Étape suivante','Cliquez sur WhatsApp pour envoyer la demande préparée']],email:'Vous préférez l’e-mail ?',form:{eyebrow:'Étude du projet',title:'Parlez-nous de votre projet',intro:'Fournissez les informations dont vous disposez déjà. Le formulaire prépare une demande structurée sur WhatsApp ; rien n’est envoyé tant que vous ne choisissez pas de continuer.',labels:{name:'Nom complet *',company:'Nom de l’entreprise',email:'E-mail professionnel *',country:'Pays de destination *',product:'Catégorie de produit *',quantity:'Volume de commande estimé *',services:'Modèle de collaboration',packaging:'État du conditionnement',launch:'Date de lancement cible',details:'Exigences du projet'},select:'Sélectionner',products:[['Fine Fragrance','Parfumerie fine'],['Body or Hair Mist','Brume corps ou cheveux'],['Home Fragrance','Parfums d’intérieur'],['Packaging Only','Conditionnement uniquement'],['Not Yet Decided','Pas encore décidé']],quantities:[['low','Faible quantité — demander une étude'],['private','Fourchette marque blanche'],['custom','Fourchette projet personnalisé'],['3,000 - 5,000 pcs','3,000–5,000 unités'],['5,000 - 10,000 pcs','5,000–10,000 unités'],['10,000+ pcs','10,000+ unités'],['Not Yet Decided','Pas encore décidé']],services:[['Private Label','Marque blanche'],['Custom Fragrance / ODM','Fragrance sur mesure / ODM'],['OEM / Contract Processing','OEM / Fabrication à façon'],['Packaging Support','Assistance au conditionnement'],['Free Fragrance Sample Request','Demande d’échantillons de fragrance gratuits']],packaging:[['Not Specified','Sélectionner le statut'],['Need Factory Recommendation','Besoin d’une recommandation de l’usine'],['Components Already Selected','Composants déjà sélectionnés'],['Customer-supplied Components','Composants fournis par le client'],['Packaging Only Project','Projet de conditionnement uniquement']],launchPlaceholder:'Mois / Année',detailsPlaceholder:'Orientation olfactive, préférences de flacon ou de conditionnement, matières fournies, échantillons de référence et autres exigences',submit:'Préparer la demande WhatsApp',note:'Vos coordonnées servent uniquement à préparer cette demande commerciale et à y répondre. Rien n’est envoyé tant que vous ne poursuivez pas sur WhatsApp. Les fichiers et images de référence peuvent être joints après l’ouverture de la conversation.'}}
  }
};

const zh = {
  hero:{eyebrow:'私人标签 · OEM · ODM',title:'中国香水定制与私人标签制造服务',text:'从香型开发、瓶器采购到灌装、包装和出口项目协调，由同一项目团队推进。',proof:['私人标签典型起订量：{{fact("privateLabelMoq")}}','样品准备：{{fact("sampleDaysShort")}}','服务全球 B2B 客户'],primary:'获取工厂报价',secondary:'申请香型样品'},
  metricLabels:['厂房面积','成立时间','受控生产车间','香型方向'],
  categories:{kicker:'产品能力',title:'围绕品牌需求规划香氛产品',text:'提供目标市场、数量、香型与包装方向，我们将评估合适的配方、组件和生产路径。',items:[['fine-fragrance','fine-fragrance.webp','香水私人标签产品','EDP · EDT · Extrait','精品香水','面向零售香水品牌的香型开发、灌装与成品包装。'],['home-fragrance','home-fragrance.webp','家居香氛产品','扩香 · 空间喷雾 · 香薰','家居香氛','根据具体配方、包装和目标市场评估可行形式。'],['body-fragrance','body-fragrance.webp','身体与发用香氛','Body Mist · Hair Mist','身体与发用香氛','适合美容、个人护理与生活方式品牌的细雾型产品。'],['packaging-solutions','packaging-solutions.webp','香水瓶器和包装组件','瓶 · 泵 · 盖 · 盒','包装解决方案','协调现货或定制组件，形成可执行的生产包装方案。']],link:'咨询项目',question:'不确定哪种生产方式更适合您的品牌？',cta:'申请产品方案建议'},
  models:{kicker:'选择合作方式',title:'三种香水项目路径',text:'根据已有资料、开发范围和目标数量选择合适的合作方式。',items:[{badge:'快速路径',title:'私人标签',text:'从适合的现有香型方向和标准组件中选择，再应用品牌名称与包装设计。',specs:[['典型起订量','{{fact("privateLabelMoq")}}'],['打样','{{fact("sampleDays")}}'],['适合','新品测试与快速上市']],link:'了解私人标签'},{badge:'灵活定制',title:'ODM 定制开发',text:'根据品牌定位、香型简报、成本与目标市场开发香型和包装。',specs:[['典型起订量','{{fact("customMoq")}}'],['开发方式','多轮样品确认'],['适合','原创品牌系列']],link:'了解 ODM',featured:true},{badge:'工厂合作',title:'OEM / 委托加工',text:'客户提供已确认的配方、组件、设计稿或技术规格，工厂按确认范围执行生产。',specs:[['典型数量','按项目评估'],['客户投入','自有配方或组件'],['适合','已有成熟标准的品牌']],link:'了解 OEM'}]},
  process:{kicker:'从需求到出货',title:'清晰的项目确认流程',text:'香型、包装、质量和生产均设置确认节点，减少批量生产前的信息偏差。',items:[['项目需求','确认市场、产品、香型、数量和预算。'],['香型打样','评估初始方向并提交反馈。'],['包装确认','确认瓶、泵、盖、装饰与外盒。'],['测试与生产','完成相容性评估和生产批准。'],['验货与运输','准备批次和运输所需资料。']],cta:'查看完整合作流程'},
  extended:{
    fragrance:{
      kicker:'香型开发',
      title:'将创意方向转化为品牌专属香型',
      text:'可以从参考香、香调家族或品牌故事开始。我们通过打样流程将需求简报转化为可供评估的香型方向。',
      families:['花香调','柑橘调','木质调','琥珀调','果香调','绿叶调','水生调','美食调'],
      checks:['提供三个初始香型方向用于评估','规划 EDP、EDT 与香精浓度方向','根据结构化反馈调整和优化配方'],
      cta:'提交香型开发需求'
    },
    manufacturing:{
      kicker:'生产能力',
      title:'支持稳定且可扩展的香水生产',
      text:'从试销项目到持续批发订单，生产按照明确的备料、调配、灌装和包装阶段推进。',
      items:['香精调配与熟化','冷却与过滤','自动灌装与泵头轧口','贴标、喷码与装盒','薄膜包装与出口装箱'],
      cta:'申请工厂介绍资料',
      caption:'受控生产环境',
      meta:'调配 · 灌装 · 装配'
    },
    quality:{
      kicker:'质量控制',
      title:'从配方到成品包装的质量检查',
      text:'在批准批量生产前，根据配方、包装组件和目标市场要求制定相应的检查方案。',
      items:[
        ['原料与组件检查','到厂香精、酒精和包装组件按照项目规格进行核对。'],
        ['稳定性评估','在设定的储存条件下观察配方的外观、气味和颜色变化。'],
        ['相容性评估','批量生产前评估配方与瓶器、泵头、密封件和装饰工艺的相容性。'],
        ['温度与光照观察','通过高温、低温和光照条件识别可能的产品表现变化。'],
        ['泄漏与喷雾检查','检查成品轧口密封、泄漏风险和喷雾表现。'],
        ['批次文件','生产与质量记录可用于支持适用的 COA、SDS 和运输资料。']
      ]
    },
    caseStudy:{
      kicker:'项目范围示例',
      title:'从创意简报到三款香型系列',
      text:'该示例展示多 SKU 上市项目可以如何规划。最终数量、周期和打样轮次需根据确认的配方与包装方案确定。',
      label:'代表性项目结构',
      stats:[['3','个 EDP 香型方向'],['5,000','每款香型瓶数'],['3','轮打样'],['35 天','示例生产周期']],
      checks:['使用现货玻璃瓶并定制表面装饰','协调瓶盖、标签和硬盒包装','准备批次文件和危险品海运资料'],
      cta:'规划类似产品系列'
    },
    export:{
      kicker:'全球出口支持',
      title:'为国际香水运输做好准备',
      text:'含酒精香水需要专业运输处理。我们协助准备所选运输路线需要的产品、批次及危险品相关资料。',
      regions:['北美','欧洲','中东','东南亚','澳大利亚与新西兰'],
      items:[
        ['危险品运输协调','为第 3 类含酒精香水货物评估专业海运和空运方案。'],
        ['SDS 与批次资料','在适用情况下准备配方和批次资料，供运输及进口审核使用。'],
        ['出口包装','根据运输路线协调外箱配置、产品防护和运输标识。'],
        ['目的地要求支持','根据目的地需求协助确认标签、外箱和物流相关要求。']
      ],
      note:'具体国家和批次的运输可用性、DDP 服务及目的地要求均需逐单确认。'
    },
    faq:{
      kicker:'询价前准备',
      title:'常见采购问题',
      text:'以下信息可帮助您在询价前准备数量、产品和包装需求。',
      cta:'查看全部常见问题',
      items:[
        ['典型起订量是多少？','使用适合的标准组件时，私人标签项目典型起订量为 {{fact("privateLabelMoq")}}，定制项目典型起订量为 {{fact("customMoq")}}。更低数量可申请个案评估，但不保证可行。'],
        ['香型样品通常需要多久？','确认需求简报和寄送安排后，初始样品通常在 {{fact("sampleDays")}} 内准备。基础评估样品免费，客户承担实际快递费用。'],
        ['香水瓶、瓶盖和外盒可以定制吗？','可以。项目可使用现货组件并定制颜色、表面工艺和印刷包装；当数量和模具预算合适时，也可以开发专用组件。'],
        ['可以提供哪些文件？','根据配方和目标市场，可提供的资料可能包括 SDS、COA、批次记录以及香精相关合规文件。'],
        ['典型生产周期是多久？','生产周期在配方和包装批准后确认。使用现货组件的项目通常更快；定制玻璃瓶、瓶盖或硬盒需要额外采购时间。'],
        ['含酒精香水如何运输？','含酒精香水通常作为第 3 类危险品（UN 1266）通过专业渠道运输，具体路线根据数量、目的地和交付要求确定。']
      ]
    },
    inquiry:{
      kicker:'启动项目',
      title:'获取报价与样品方案',
      text:'请告诉我们计划生产的产品、销售市场和预计数量。表单会为工厂项目团队整理一条结构化 WhatsApp 询盘。',
      expectations:[['需要提供','产品类型、预计数量和目的地'],['您将收到','建议合作路径、起订量和样品方案'],['下一步','通过 WhatsApp 发送整理后的询盘']],
      email:'更习惯使用邮箱？',
      form:contactForms['zh-CN'].form
    }
  },
  final:{title:'准备讨论您的香水项目？',text:'提交产品类型、预计数量和定制需求，我们将先进行可行性评估。',cta:'提交项目需求'}
};

module.exports = { en, 'zh-CN': zh, es, ar, fr };
