module.exports = {
  en: {
    hero:{eyebrow:'Private Label · OEM · ODM',title:'Choose the Right Manufacturing Route for Your Fragrance Project',text:'Start with an existing fragrance and stock packaging, develop a customized product, or bring us your own materials, artwork or reference sample.',primary:'Discuss Your Project',secondary:'Compare Service Models'},
    factLabels:['Typical Private Label MOQ','Typical Custom Project MOQ','Standard Raw-Material Procurement','Flexible Processing Options'], factValues:['{{fact("privateLabelMoq")}}','{{fact("customMoq")}}','Approx. 5 Days','4 Models'],
    routesIntro:{kicker:'Choose Your Route',title:'Three Practical Ways to Work with Our Factory',text:'The right model depends on what you already have, how much development you need and which components must be sourced or customized.'},
    routes:[
      {id:'private-label',badge:'Fastest Route',quantity:'Typical {{fact("privateLabelMoq")}}',title:'Private Label',text:'Choose from existing fragrance directions and available bottle formats, then apply your own brand decoration and packaging.',details:[['You provide','Brand name, artwork and target market'],['Factory handles','Product selection, filling, labeling, assembly and packing'],['Best suited for','Market tests, first launches and smaller brand collections']],link:'Start a Private Label Project'},
      {id:'odm',badge:'Custom Development',quantity:'{{config.services.odm.moq.typicalPcs}}',title:'ODM / Custom Project',text:'Develop a fragrance and coordinated pack from your brief using stock or customized components that fit the approved quantity and budget.',details:[['You provide','Concept, scent direction, budget and positioning'],['Factory handles','Sampling, material sourcing, compounding, filling and finished packing'],['Best suited for','Original fragrance collections and differentiated brand projects']],link:'Discuss a Custom Project'},
      {id:'oem',badge:'Flexible Inputs',quantity:'Project-based',title:'OEM / Contract Processing',text:'Bring your formula, materials, technical specification, artwork or approved sample. We define the production scope around the inputs you supply.',details:[['You provide','Formula, components, artwork, specification or reference sample'],['Factory handles','Agreed processing, filling, assembly, inspection and packing stages'],['Best suited for','Brands with an established product standard or supply chain']],link:'Request an OEM Review'}
    ],
    terms:'Typical starting quantities apply to suitable standard components. Smaller pilot runs can be reviewed case by case through WhatsApp, but approval is not guaranteed. Lower quantities may limit fragrance, bottle, decoration and packaging choices and may affect unit price.',
    options:{kicker:'Flexible Cooperation',title:'Processing Options Based on What You Already Have',text:'We confirm the responsibility for formulas, raw materials, packaging components and production before quoting.',items:[['Contract Processing','You supply the agreed materials or components; the factory completes the confirmed processing stages.','Customer-supplied materials'],['Full-Package Production','We coordinate approved materials and production, from component purchasing through filling and packing.','Materials + manufacturing'],['Build to Artwork or Specs','Production is organized around your supplied artwork, drawings and technical requirements after feasibility review.','Customer-supplied design files'],['Build to Reference Sample','Provide an approved sample for evaluation. We define achievable fragrance, packaging and process specifications before sampling.','Customer-supplied reference']]},
    process:{kicker:'From Brief to Finished Goods',title:'A Process with Clear Confirmation Points',visualTitle:'Real Production Environment',visualMeta:'Compounding · Filling · Assembly',items:[['Project Brief & Route Selection','Confirm product type, quantity, supplied inputs, destination, budget and required customization.'],['Quotation & Specification','Define the cooperation model, production scope, materials, quality requirements and commercial terms.'],['Sampling & Component Review','Evaluate fragrance samples, bottles, pumps, caps, artwork and packaging before approval.'],['Final Approval','Lock the formula, components, decoration files and approved reference before purchasing and production.'],['Raw-Material Procurement','Standard raw-material purchasing is approximately 5 days after confirmation. Customized components may require additional time.'],['Production & In-Process Checks','Complete the agreed compounding, filling, sealing, assembly and packaging operations with inspection points.'],['Final Inspection & Shipment Preparation','Confirm finished packing, batch information and the documentation required for the selected freight route.']]},
    samples:{kicker:'Evaluate Before Production',title:'Free Fragrance Sample Kit',intro:'Evaluate the fragrance direction before approving production. Basic evaluation samples are provided free of charge; you only pay the actual courier cost to your destination.',mediaTitle:'Factory Sample Showroom',mediaMeta:'Fragrance evaluation · Component review',labels:['Sample Cost','Typical Set','Preparation Time','Courier Cost'],values:['Free','{{fact("sampleSet")}}','{{fact("sampleDays")}}','Actual Cost'],notes:['Courier pricing is calculated according to the destination and confirmed with you before dispatch.','Special formulations, additional revision rounds or customized packaging samples are reviewed separately if extra costs apply.'],cta:'Request Free Samples'},
    operations:{kicker:'Available Operations',title:'Practical Production and Packing Support',text:'The exact operation list is confirmed against your formula, components and finished-product specification.',items:[['Compounding','Formula preparation and batch mixing'],['Filling','Perfume filling to approved volume'],['Film Sealing','Protective film application where specified'],['Component Assembly','Pump, cap and pack assembly'],['Manual Boxing','Manual placement and presentation checks'],['Final Packing','Finished-pack inspection and carton packing']]},
    faq:{kicker:'Before You Request a Quote',title:'Important Project Conditions',text:'Send us your product type, quantity and available files or samples so the factory can confirm the correct route.',items:[['What are the typical starting quantities?','{{config.policies.moq}}'],['Does the 5-day period mean total delivery time?','No. Approximately 5 days refers to purchasing standard raw materials after project confirmation. Sampling, customized packaging, production, inspection and shipping are scheduled separately.'],['Can we supply our own materials or product sample?','Yes. We can review customer-supplied materials, artwork, specifications or reference samples and define a contract-processing scope after feasibility assessment.'],['Which operations can the factory complete?','Available operations include compounding, filling, film sealing, component assembly, packing and manual boxing. The confirmed list depends on the product specification.']]},
    final:{eyebrow:'Start with the information you already have',title:'Let the Factory Recommend the Right Cooperation Model',text:'Share your target product, estimated quantity, destination and any available artwork, formula or reference sample.',cta:'Request Project Review'}
  },
  'zh-CN': {
    hero:{eyebrow:'私人标签 · OEM · ODM',title:'选择适合香水项目的生产方式',text:'从现有香型和标准包装快速启动，开发定制产品，或提供自有配方、组件、设计稿和参考样品。',primary:'沟通项目需求',secondary:'比较合作方式'},
    factLabels:['私人标签典型起订量','定制项目典型起订量','典型评估样品','典型准备时间'], factValues:['{{fact("privateLabelMoq")}}','{{fact("customMoq")}}','{{fact("sampleSet")}}','{{fact("sampleDays")}}'],
    routesIntro:{kicker:'选择合作路径',title:'三种与工厂合作的方式',text:'合适的方式取决于您已有的资料、需要开发的范围，以及哪些组件需要采购或定制。'},
    routes:[
      {id:'private-label',badge:'快速路径',quantity:'典型 {{fact("privateLabelMoq")}}',title:'私人标签',text:'从适合的现有香型方向和可用瓶器中选择，再应用品牌装饰和外包装。',details:[['客户提供','品牌名称、设计稿、目标市场和商业要求'],['工厂支持','香型选择、组件采购、灌装、贴标、装盒与包装'],['适合项目','市场测试、首次上市和小型品牌系列']],link:'启动私人标签项目'},
      {id:'odm',badge:'定制开发',quantity:'典型 {{fact("customMoq")}}',title:'ODM 定制项目',text:'根据品牌定位、目标客群、香型简报、预算和市场要求开发香型与包装方案。',details:[['客户提供','品牌定位、嗅觉方向、目标价格和上市市场'],['工厂支持','香型打样、组件选择、采购、调配、灌装和成品包装'],['适合项目','原创香水系列和差异化品牌项目']],link:'讨论定制项目'},
      {id:'oem',badge:'灵活来料',quantity:'按项目评估',title:'OEM / 委托加工',text:'客户提供配方、原料、组件、设计稿、技术规格或参考样品，生产范围在可行性评估后确认。',details:[['客户提供','配方、组件、设计稿、规格或批准参考样品'],['工厂支持','约定的加工、灌装、装配、检验和包装工序'],['适合项目','已有成熟产品标准或供应链的品牌']],link:'申请 OEM 评估'}
    ],
    terms:'起订量为适合标准组件项目的典型参考，并非绝对承诺。低于标准数量的项目可通过 WhatsApp 申请个案评估，但不保证可行。',
    process:{kicker:'从需求到成品',title:'设置明确确认节点的项目流程',visualTitle:'实际生产环境',visualMeta:'调配 · 灌装 · 装配',items:[['需求与可行性','确认产品、数量、目标市场、预算、香型、客户来料和包装范围。'],['报价与项目规格','明确合作方式、生产范围、材料、质量要求和商业条件。'],['香型与组件样品','评估香型、瓶器、泵头、瓶盖、装饰、设计稿和外盒。'],['最终批准','锁定配方、组件、装饰文件和批量生产参考标准。'],['采购与生产安排','按确认范围采购材料并安排调配、灌装、封口、装配和包装。'],['检验与运输准备','确认成品包装、批次信息和所选运输路线需要的资料。']]},
    samples:{kicker:'生产前评估',title:'基础香型评估样品',intro:'基础香型样品免费提供，客户只需承担寄往目的地的实际快递费用。',mediaTitle:'工厂样品展示区',mediaMeta:'香型评估 · 组件确认',labels:['样品费用','典型套装','准备时间','快递费用'],values:['免费','{{fact("sampleSet")}}','{{fact("sampleDays")}}','按实际费用'],notes:['快递价格根据目的地计算，并在寄出前与客户确认。','特殊配方、额外修改轮次或定制包装样品需另行评估。'],cta:'申请样品'}
  }
};
