module.exports = {
  en: {
    hero:{eyebrow:'Private Label · OEM · ODM',title:'Choose the Right Manufacturing Route for Your Fragrance Project',text:'Start with an existing fragrance and stock packaging, develop a customized product, or bring us your own materials, artwork or reference sample.',primary:'Discuss Your Project',secondary:'Compare Service Models'},
    factLabels:['Typical Private Label MOQ','Typical Custom Project MOQ','Standard Raw-Material Procurement','Flexible Processing Options'], factValues:['{{fact("privateLabelMoq")}}','{{fact("customMoq")}}','Approx. 5 Days','4 Models'],
    routesIntro:{kicker:'Choose Your Route',title:'Three Practical Ways to Work with Our Factory',text:'The right model depends on what you already have, how much development you need and which components must be sourced or customized.'},
    routes:[
      {id:'private-label',badge:'Fastest Route',quantity:'Typical {{fact("privateLabelMoq")}}',title:'Private Label',text:'Choose from existing fragrance directions and available bottle formats, then apply your own brand decoration and packaging.',details:[['You provide','Brand name, artwork and target market'],['Factory handles','Product selection, filling, labeling, assembly and packing'],['Best suited for','Market tests, first launches and smaller brand collections']],link:'Start a Private Label Project'},
      {id:'odm',badge:'Custom Development',quantity:'{{config.services.odm.moq.typicalPcs}}',title:'ODM / Custom Project',text:'Develop a fragrance and coordinated pack from your brief using stock or customized components that fit the approved quantity and budget.',details:[['You provide','Concept, scent direction, budget and positioning'],['Factory handles','Sampling, material sourcing, compounding, filling and finished packing'],['Best suited for','Original fragrance collections and differentiated brand projects']],link:'Discuss a Custom Project'},
      {id:'oem',badge:'Flexible Inputs',quantity:'Project-based',title:'OEM / Contract Processing',text:'Bring your formula, materials, technical specification, artwork or approved sample. We define the production scope around the inputs you supply.',details:[['You provide','Formula, components, artwork, specification or reference sample'],['Factory handles','Agreed processing, filling, assembly, inspection and packing stages'],['Best suited for','Brands with an established product standard or supply chain']],link:'Request an OEM Review'}
    ],
    terms:'Typical starting quantities apply to suitable standard components. Smaller pilot runs can be reviewed case by case through WhatsApp, but approval is not guaranteed. Lower quantities may limit fragrance, bottle, decoration and packaging choices and may affect unit price.',
    options:{kicker:'Flexible Cooperation',title:'Processing Options Based on What You Already Have',text:'We confirm the responsibility for formulas, raw materials, packaging components and production before quoting.',items:[['Contract Processing','You supply the agreed materials or components; the factory completes the confirmed processing stages.','Customer-supplied materials'],['Full-Package Production','We coordinate approved materials and production, from component purchasing through filling and packing.','Materials + manufacturing'],['Build to Artwork or Specs','Production is organized around your supplied artwork, drawings and technical requirements after feasibility review.','Customer-supplied design files'],['Build to Reference Sample','Provide an approved sample for evaluation. We define achievable fragrance, packaging and process specifications before sampling.','Customer-supplied reference']]},
    process:{kicker:'From Brief to Finished Goods',title:'A Process with Clear Confirmation Points',visualTitle:'Real Production Environment',visualMeta:'Compounding · Filling · Assembly',items:[['Project Brief & Route Selection','Confirm product type, quantity, supplied inputs, destination, budget and required customization.'],['Quotation & Specification','Define the cooperation model, production scope, materials, quality requirements and commercial terms.'],['Sampling & Component Review','Evaluate fragrance samples, bottles, pumps, caps, artwork and packaging before approval.'],['Final Approval','Lock the formula, components, decoration files and approved reference before purchasing and production.'],['Raw-Material Procurement','Standard raw-material purchasing is approximately 5 days after confirmation. Customized components may require additional time.'],['Production & In-Process Checks','Complete the agreed compounding, filling, sealing, assembly and packaging operations with inspection points.'],['Final Inspection & Shipment Preparation','Confirm finished packing, batch information and the documentation required for the selected freight route.']]},
    samples:{kicker:'Evaluate Before Production',title:'Free Fragrance Sample Kit',intro:'Evaluate the fragrance direction before approving production. Basic evaluation samples are provided free of charge; you only pay the actual courier cost to your destination.',mediaTitle:'Factory Sample Showroom',mediaMeta:'Fragrance evaluation · Component review',labels:['Sample Cost','Typical Set','Preparation Time','Courier Cost'],values:['Free','{{fact("sampleSet")}}','{{fact("sampleDays")}}','Actual Cost'],notes:['Courier pricing is calculated according to the destination and confirmed with you before dispatch.','Special formulations, additional revision rounds or customized packaging samples are reviewed separately if extra costs apply.'],cta:'Request Free Samples'},
    operations:{kicker:'Available Operations',title:'Practical Production and Packing Support',text:'The exact operation list is confirmed against your formula, components and finished-product specification.',items:[['Compounding','Formula preparation and batch mixing'],['Filling','Perfume filling to approved volume'],['Film Sealing','Protective film application where specified'],['Component Assembly','Pump, cap and pack assembly'],['Manual Boxing','Manual placement and presentation checks'],['Final Packing','Finished-pack inspection and carton packing']]},
    faq:{kicker:'Before You Request a Quote',title:'Important Project Conditions',text:'Send us your product type, quantity and available files or samples so the factory can confirm the correct route.',items:[['What are the typical starting quantities?','{{config.policies.moq}}'],['Does the 5-day period mean total delivery time?','No. Approximately 5 days refers to purchasing standard raw materials after project confirmation. Sampling, customized packaging, production, inspection and shipping are scheduled separately.'],['Can we supply our own materials or product sample?','Yes. We can review customer-supplied materials, artwork, specifications or reference samples and define a contract-processing scope after feasibility assessment.'],['Which operations can the factory complete?','Available operations include compounding, filling, film sealing, component assembly, packing and manual boxing. The confirmed list depends on the product specification.']]},
    final:{eyebrow:'Start with the information you already have',title:'Let the Factory Recommend the Right Cooperation Model',text:'Share your target product, estimated quantity, destination and any available artwork, formula or reference sample.',cta:'Request Project Review'}
  },
  'zh-CN': {
    hero:{eyebrow:'私人标签 · OEM · ODM',title:'选择适合香水项目的生产方式',text:'从现有香型和标准包装快速启动，开发定制产品，或提供自有配方、组件、设计稿和参考样品。',primary:'沟通项目需求',secondary:'比较合作方式'},
    factLabels:['私人标签典型起订量','定制项目典型起订量','典型评估样品','典型准备时间'], factValues:['{{fact("privateLabelMoq")}}','{{fact("customMoq")}}','{{fact("sampleSet")}}','{{fact("sampleDays")}}'],
    routesIntro:{kicker:'选择合作路径',title:'三种与工厂合作的方式',text:'合适的方式取决于您已有的资料、需要开发的范围，以及哪些组件需要采购或定制。'},
    routes:[
      {id:'private-label',badge:'快速路径',quantity:'典型 {{fact("privateLabelMoq")}}',title:'私人标签',text:'从适合的现有香型方向和可用瓶器中选择，再应用品牌装饰和外包装。',details:[['客户提供','品牌名称、设计稿、目标市场和商业要求'],['工厂支持','香型选择、组件采购、灌装、贴标、装盒与包装'],['适合项目','市场测试、首次上市和小型品牌系列']],link:'启动私人标签项目'},
      {id:'odm',badge:'定制开发',quantity:'典型 {{fact("customMoq")}}',title:'ODM 定制项目',text:'根据品牌定位、目标客群、香型简报、预算和市场要求开发香型与包装方案。',details:[['客户提供','品牌定位、嗅觉方向、目标价格和上市市场'],['工厂支持','香型打样、组件选择、采购、调配、灌装和成品包装'],['适合项目','原创香水系列和差异化品牌项目']],link:'讨论定制项目'},
      {id:'oem',badge:'灵活来料',quantity:'按项目评估',title:'OEM / 委托加工',text:'客户提供配方、原料、组件、设计稿、技术规格或参考样品，生产范围在可行性评估后确认。',details:[['客户提供','配方、组件、设计稿、规格或批准参考样品'],['工厂支持','约定的加工、灌装、装配、检验和包装工序'],['适合项目','已有成熟产品标准或供应链的品牌']],link:'申请 OEM 评估'}
    ],
    terms:'典型起订量适用于采用合适标准组件的项目。低于标准数量的试单可通过 WhatsApp 申请个案评估，但不保证获批。较低数量可能限制香型、瓶器、装饰和包装选择，并影响单位价格。',
    options:{kicker:'灵活合作',title:'根据客户现有资料安排加工方式',text:'报价前会明确配方、原料、包装组件和生产各环节的责任归属。',items:[['委托加工','客户提供双方约定的材料或组件，工厂完成已确认的加工工序。','客户提供材料'],['全包生产','由工厂协调已批准的材料和生产，从组件采购到灌装及包装。','材料 + 生产'],['按设计稿或规格生产','可行性审核后，按照客户提供的设计稿、图纸和技术要求组织生产。','客户提供设计文件'],['按参考样品开发','客户提供批准参考样品，工厂在打样前明确可实现的香型、包装和工艺规格。','客户提供参考样品']]},
    process:{kicker:'从需求到成品',title:'设置明确确认节点的项目流程',visualTitle:'实际生产环境',visualMeta:'调配 · 灌装 · 装配',items:[['项目需求与路径选择','确认产品类型、数量、客户提供资料、目标市场、预算和定制范围。'],['报价与项目规格','明确合作方式、生产范围、材料、质量要求和商业条件。'],['香型与组件样品','评估香型样品、瓶器、泵头、瓶盖、设计稿和包装。'],['最终批准','锁定配方、组件、装饰文件和采购及生产所依据的批准标准。'],['原料与组件采购','项目确认后，常规原料采购约需 5 天；定制组件可能需要更长时间。'],['生产与过程检验','按照约定完成调配、灌装、封口、装配和包装，并设置过程检查。'],['最终检验与出货准备','确认成品包装、批次信息和所选运输路线需要的文件。']]},
    samples:{kicker:'生产前评估',title:'免费香型评估套装',intro:'生产批准前先评估香型方向。基础评香样品免费提供，客户只需承担寄往目的地的实际快递费用。',mediaTitle:'工厂样品展示区',mediaMeta:'香型评估 · 组件确认',labels:['样品费用','典型套装','准备时间','快递费用'],values:['免费','{{fact("sampleSet")}}','{{fact("sampleDays")}}','按实际费用'],notes:['快递价格根据目的地计算，并在寄出前与客户确认。','特殊配方、额外修改轮次或定制包装样品如产生额外费用，将另行评估确认。'],cta:'申请免费样品'},
    operations:{kicker:'可提供的工序',title:'实际生产与包装支持',text:'具体工序会根据配方、组件和成品规格逐项确认。',items:[['调配','按照批准配方准备并混合批次料液'],['灌装','按照批准容量灌装香水'],['覆膜封装','按规格要求进行保护膜封装'],['组件装配','完成泵头、瓶盖和包装组件装配'],['人工装盒','人工装盒并检查产品呈现'],['成品包装','执行成品检查和外箱包装']]},
    faq:{kicker:'申请报价前',title:'重要项目条件',text:'提供产品类型、数量以及现有文件或样品，以便工厂确认正确合作路径。',items:[['典型起订量是多少？','采用合适标准组件时，私人标签项目的典型起订量为 {{fact("privateLabelMoq")}}，定制香型项目通常从 {{fact("customMoq")}} 开始。实际数量取决于配方、瓶器、装饰、包装和客供材料。'],['5 天是否代表总交期？','不是。约 5 天仅指项目确认后采购适用的常规原料。打样、定制包装、生产、检验和运输需要分别排期。'],['可以提供自有材料或产品样品吗？','可以。工厂可评估客户提供的材料、设计稿、规格或参考样品，并在可行性审核后确定委托加工范围。'],['工厂可以完成哪些工序？','可提供调配、灌装、覆膜封装、组件装配、包装和人工装盒等工序，最终清单取决于确认的产品规格。']]},
    final:{eyebrow:'从您已有的资料开始',title:'由工厂建议合适的合作方式',text:'请提供目标产品、预计数量、目的地，以及现有设计稿、配方或参考样品。',cta:'申请项目评估'}
  },
  es: {
    hero:{eyebrow:'Marca privada · OEM · ODM',title:'Elija la modalidad de fabricación adecuada para su proyecto de perfumería',text:'Comience con una fragancia existente y envases de stock, desarrolle un producto personalizado o proporciónenos sus propios materiales, artes gráficas o muestra de referencia.',primary:'Hablemos de su proyecto',secondary:'Comparar modelos de servicio'},
    factLabels:['MOQ habitual para marca privada','MOQ habitual para proyectos personalizados','Adquisición estándar de materias primas','Opciones de procesamiento flexibles'], factValues:['{{fact("privateLabelMoq")}}','{{fact("customMoq")}}','Aprox. 5 días','4 modelos'],
    routesIntro:{kicker:'Elija su modalidad',title:'Tres formas prácticas de trabajar con nuestra fábrica',text:'El modelo adecuado depende de los elementos de los que ya dispone, del nivel de desarrollo necesario y de los componentes que deban adquirirse o personalizarse.'},
    routes:[
      {id:'private-label',badge:'La modalidad más rápida',quantity:'Habitualmente {{fact("privateLabelMoq")}}',title:'Marca privada',text:'Elija entre las líneas olfativas existentes y los formatos de frasco disponibles y, a continuación, aplique la decoración y el embalaje de su propia marca.',details:[['Usted proporciona','Nombre de la marca, artes gráficas y mercado objetivo'],['La fábrica se encarga de','Selección del producto, llenado, etiquetado, montaje y embalaje'],['Especialmente indicado para','Pruebas de mercado, primeros lanzamientos y colecciones de marca más pequeñas']],link:'Iniciar un proyecto de marca privada'},
      {id:'odm',badge:'Desarrollo personalizado',quantity:'{{config.services.odm.moq.typicalPcs}}',title:'ODM / Proyecto personalizado',text:'Desarrolle una fragancia y un conjunto de envase coordinado a partir de sus especificaciones, utilizando componentes de stock o personalizados que se ajusten a la cantidad y al presupuesto aprobados.',details:[['Usted proporciona','Concepto, orientación olfativa, presupuesto y posicionamiento'],['La fábrica se encarga de','Muestreo, adquisición de materiales, composición, llenado y embalaje final'],['Especialmente indicado para','Colecciones de fragancias originales y proyectos de marca diferenciados']],link:'Consultar un proyecto personalizado'},
      {id:'oem',badge:'Insumos flexibles',quantity:'Según el proyecto',title:'OEM / Fabricación por contrato',text:'Proporcione su fórmula, materiales, especificaciones técnicas, artes gráficas o muestra aprobada. Definiremos el alcance de producción en función de los insumos que suministre.',details:[['Usted proporciona','Fórmula, componentes, artes gráficas, especificaciones o muestra de referencia'],['La fábrica se encarga de','Las etapas acordadas de procesamiento, llenado, montaje, inspección y embalaje'],['Especialmente indicado para','Marcas con un estándar de producto o una cadena de suministro consolidados']],link:'Solicitar una evaluación OEM'}
    ],
    terms:'Las cantidades iniciales habituales se aplican a componentes estándar adecuados. Las series piloto más pequeñas pueden evaluarse caso por caso a través de WhatsApp, pero su aprobación no está garantizada. Las cantidades inferiores pueden limitar las opciones de fragancia, frasco, decoración y embalaje, y afectar al precio unitario.',
    options:{kicker:'Cooperación flexible',title:'Opciones de procesamiento basadas en los elementos de los que ya dispone',text:'Antes de cotizar, confirmamos la responsabilidad sobre las fórmulas, las materias primas, los componentes de embalaje y la producción.',items:[['Fabricación por contrato','Usted suministra los materiales o componentes acordados; la fábrica completa las etapas de procesamiento confirmadas.','Materiales suministrados por el cliente'],['Producción integral','Coordinamos los materiales y la producción aprobados, desde la compra de componentes hasta el llenado y el embalaje.','Materiales + fabricación'],['Producción según artes gráficas o especificaciones','La producción se organiza conforme a las artes gráficas, los planos y los requisitos técnicos que usted suministre, tras revisar su viabilidad.','Archivos de diseño suministrados por el cliente'],['Producción según muestra de referencia','Proporcione una muestra aprobada para su evaluación. Antes del muestreo, definiremos las especificaciones viables de fragancia, embalaje y proceso.','Referencia suministrada por el cliente']]},
    process:{kicker:'De las especificaciones al producto terminado',title:'Un proceso con puntos de confirmación claros',visualTitle:'Entorno de producción real',visualMeta:'Composición · Llenado · Montaje',items:[['Especificaciones del proyecto y elección de modalidad','Confirmar el tipo de producto, la cantidad, los insumos suministrados, el destino, el presupuesto y la personalización requerida.'],['Cotización y especificaciones','Definir el modelo de cooperación, el alcance de producción, los materiales, los requisitos de calidad y las condiciones comerciales.'],['Muestreo y revisión de componentes','Evaluar las muestras de fragancia, los frascos, las bombas, los tapones, las artes gráficas y el embalaje antes de su aprobación.'],['Aprobación final','Fijar la fórmula, los componentes, los archivos de decoración y la referencia aprobada antes de las compras y la producción.'],['Adquisición de materias primas','La compra de materias primas estándar tarda aproximadamente 5 días después de la confirmación. Los componentes personalizados pueden requerir más tiempo.'],['Producción y controles durante el proceso','Completar las operaciones acordadas de composición, llenado, sellado, montaje y embalaje con puntos de inspección.'],['Inspección final y preparación del envío','Confirmar el embalaje final, la información del lote y la documentación requerida para la ruta de transporte seleccionada.']]},
    samples:{kicker:'Evalúe antes de producir',title:'Kit gratuito de muestras de fragancias',intro:'Evalúe la orientación olfativa antes de aprobar la producción. Las muestras básicas de evaluación se proporcionan gratuitamente; usted solo abona el coste real de mensajería hasta su destino.',mediaTitle:'Sala de exposición de muestras de fábrica',mediaMeta:'Evaluación olfativa · Revisión de componentes',labels:['Coste de las muestras','Conjunto habitual','Tiempo de preparación','Coste de mensajería'],values:['Gratis','{{fact("sampleSet")}}','{{fact("sampleDays")}}','Coste real'],notes:['El precio de la mensajería se calcula según el destino y se confirma con usted antes del envío.','Las formulaciones especiales, las rondas de revisión adicionales o las muestras de embalaje personalizado se evalúan por separado si conllevan costes adicionales.'],cta:'Solicitar muestras gratuitas'},
    operations:{kicker:'Operaciones disponibles',title:'Asistencia práctica para producción y embalaje',text:'La lista exacta de operaciones se confirma en función de su fórmula, sus componentes y las especificaciones del producto terminado.',items:[['Composición','Preparación de la fórmula y mezcla del lote'],['Llenado','Llenado del perfume al volumen aprobado'],['Sellado con película','Aplicación de película protectora cuando se especifique'],['Montaje de componentes','Montaje de bomba, tapón y envase'],['Encajado manual','Colocación manual y controles de presentación'],['Embalaje final','Inspección del envase terminado y embalaje en cajas de transporte']]},
    faq:{kicker:'Antes de solicitar una cotización',title:'Condiciones importantes del proyecto',text:'Envíenos el tipo de producto, la cantidad y los archivos o muestras disponibles para que la fábrica pueda confirmar la modalidad adecuada.',items:[['¿Cuáles son las cantidades iniciales habituales?','{{config.policies.moq}}'],['¿El plazo de 5 días corresponde al tiempo total de entrega?','No. Los aproximadamente 5 días se refieren a la compra de materias primas estándar después de confirmar el proyecto. El muestreo, el embalaje personalizado, la producción, la inspección y el envío se programan por separado.'],['¿Podemos suministrar nuestros propios materiales o una muestra del producto?','Sí. Podemos evaluar materiales, artes gráficas, especificaciones o muestras de referencia suministrados por el cliente y definir el alcance de la fabricación por contrato tras analizar su viabilidad.'],['¿Qué operaciones puede realizar la fábrica?','Las operaciones disponibles incluyen composición, llenado, sellado con película, montaje de componentes, embalaje y encajado manual. La lista confirmada depende de las especificaciones del producto.']]},
    final:{eyebrow:'Comience con la información de la que ya dispone',title:'Deje que la fábrica le recomiende el modelo de cooperación adecuado',text:'Comparta el producto objetivo, la cantidad estimada, el destino y cualquier arte gráfica, fórmula o muestra de referencia disponible.',cta:'Solicitar evaluación del proyecto'}
  },
  ar: {
    hero:{eyebrow:'علامة خاصة · OEM · ODM',title:'اختر مسار التصنيع المناسب لمشروع العطور الخاص بك',text:'ابدأ بعطر قائم وعبوات متوفرة في المخزون، أو طوّر منتجًا مخصصًا، أو زوّدنا بموادك أو ملفاتك الفنية أو عينتك المرجعية.',primary:'ناقش مشروعك',secondary:'قارن نماذج الخدمة'},
    factLabels:['الحد الأدنى المعتاد لطلب العلامة الخاصة','الحد الأدنى المعتاد لطلب المشروع المخصص','التوريد القياسي للمواد الخام','خيارات معالجة مرنة'], factValues:['{{fact("privateLabelMoq")}}','{{fact("customMoq")}}','نحو 5 أيام','4 نماذج'],
    routesIntro:{kicker:'اختر مسارك',title:'ثلاث طرق عملية للعمل مع مصنعنا',text:'يعتمد النموذج المناسب على ما يتوفر لديك بالفعل، وحجم التطوير المطلوب، والمكونات التي يلزم توريدها أو تخصيصها.'},
    routes:[
      {id:'private-label',badge:'المسار الأسرع',quantity:'المعتاد {{fact("privateLabelMoq")}}',title:'العلامة الخاصة',text:'اختر من التوجهات العطرية القائمة وأشكال الزجاجات المتاحة، ثم طبّق زخارف علامتك التجارية وعبواتها.',details:[['ما تقدمه','اسم العلامة التجارية والملفات الفنية والسوق المستهدف'],['ما يتولاه المصنع','اختيار المنتج والتعبئة ووضع الملصقات والتجميع والتغليف'],['الأنسب لـ','اختبارات السوق وعمليات الإطلاق الأولى ومجموعات العلامات التجارية الأصغر']],link:'ابدأ مشروع علامة خاصة'},
      {id:'odm',badge:'تطوير مخصص',quantity:'{{config.services.odm.moq.typicalPcs}}',title:'ODM / مشروع مخصص',text:'طوّر عطرًا وعبوة متناسقة انطلاقًا من موجزك، باستخدام مكونات متوفرة في المخزون أو مخصصة تتوافق مع الكمية والميزانية المعتمدتين.',details:[['ما تقدمه','المفهوم والتوجه العطري والميزانية والتموضع'],['ما يتولاه المصنع','إعداد العينات وتوريد المواد والتركيب والتعبئة والتغليف النهائي'],['الأنسب لـ','مجموعات العطور الأصلية ومشروعات العلامات التجارية المتميزة']],link:'ناقش مشروعًا مخصصًا'},
      {id:'oem',badge:'مدخلات مرنة',quantity:'بحسب المشروع',title:'OEM / التصنيع التعاقدي',text:'زوّدنا بتركيبتك أو موادك أو مواصفاتك الفنية أو ملفاتك الفنية أو عينتك المعتمدة. نحدد نطاق الإنتاج وفقًا للمدخلات التي توفرها.',details:[['ما تقدمه','التركيبة أو المكونات أو الملفات الفنية أو المواصفات أو العينة المرجعية'],['ما يتولاه المصنع','مراحل المعالجة والتعبئة والتجميع والفحص والتغليف المتفق عليها'],['الأنسب لـ','العلامات التجارية التي لديها معيار منتج أو سلسلة توريد راسخة']],link:'اطلب مراجعة OEM'}
    ],
    terms:'تنطبق كميات البدء المعتادة عند استخدام مكونات قياسية مناسبة. ويمكن مراجعة دفعات تجريبية أصغر لكل حالة على حدة عبر WhatsApp، لكن الموافقة غير مضمونة. وقد تحد الكميات الأقل من خيارات العطر والزجاجة والزخرفة والعبوة، كما قد تؤثر في سعر الوحدة.',
    options:{kicker:'تعاون مرن',title:'خيارات معالجة تستند إلى ما يتوفر لديك بالفعل',text:'نؤكد قبل تقديم عرض السعر مسؤولية كل طرف عن التركيبات والمواد الخام ومكونات العبوة والإنتاج.',items:[['التصنيع التعاقدي','تورد المواد أو المكونات المتفق عليها، ويستكمل المصنع مراحل المعالجة المؤكدة.','مواد يوردها العميل'],['الإنتاج المتكامل','ننسق المواد والإنتاج المعتمدين، بدءًا من شراء المكونات وحتى التعبئة والتغليف.','المواد + التصنيع'],['الإنتاج وفق الملفات الفنية أو المواصفات','يُنظم الإنتاج وفق الملفات الفنية والرسومات والمتطلبات التقنية التي تقدمها بعد مراجعة الجدوى.','ملفات تصميم يقدمها العميل'],['الإنتاج وفق عينة مرجعية','قدّم عينة معتمدة للتقييم. ونحدد قبل إعداد العينات مواصفات العطر والعبوة والعملية القابلة للتنفيذ.','مرجع يقدمه العميل']]},
    process:{kicker:'من الموجز إلى المنتجات النهائية',title:'عملية تتضمن نقاط تأكيد واضحة',visualTitle:'بيئة إنتاج فعلية',visualMeta:'التركيب · التعبئة · التجميع',items:[['موجز المشروع واختيار المسار','تأكيد نوع المنتج والكمية والمدخلات المقدمة والوجهة والميزانية ومستوى التخصيص المطلوب.'],['عرض السعر والمواصفات','تحديد نموذج التعاون ونطاق الإنتاج والمواد ومتطلبات الجودة والشروط التجارية.'],['إعداد العينات ومراجعة المكونات','تقييم عينات العطر والزجاجات والمضخات والأغطية والملفات الفنية والعبوات قبل الاعتماد.'],['الاعتماد النهائي','تثبيت التركيبة والمكونات وملفات الزخرفة والمرجع المعتمد قبل الشراء والإنتاج.'],['توريد المواد الخام','يستغرق شراء المواد الخام القياسية نحو 5 أيام بعد التأكيد. وقد تتطلب المكونات المخصصة وقتًا إضافيًا.'],['الإنتاج والفحوص أثناء العملية','استكمال عمليات التركيب والتعبئة والإحكام والتجميع والتغليف المتفق عليها، مع نقاط للفحص.'],['الفحص النهائي والتحضير للشحن','تأكيد التغليف النهائي ومعلومات الدفعة والمستندات المطلوبة لمسار الشحن المحدد.']]},
    samples:{kicker:'قيّم قبل الإنتاج',title:'مجموعة مجانية من عينات العطور',intro:'قيّم التوجه العطري قبل اعتماد الإنتاج. تُقدم عينات التقييم الأساسية مجانًا، ولا تتحمل سوى التكلفة الفعلية لخدمة التوصيل إلى وجهتك.',mediaTitle:'صالة عرض عينات المصنع',mediaMeta:'تقييم العطر · مراجعة المكونات',labels:['تكلفة العينة','المجموعة المعتادة','مدة التحضير','تكلفة التوصيل'],values:['مجانًا','{{fact("sampleSet")}}','{{fact("sampleDays")}}','التكلفة الفعلية'],notes:['يُحتسب سعر خدمة التوصيل وفقًا للوجهة ويُؤكد معك قبل الإرسال.','تُراجع التركيبات الخاصة أو جولات التعديل الإضافية أو عينات العبوات المخصصة بصورة منفصلة إذا ترتبت عليها تكاليف إضافية.'],cta:'اطلب عينات مجانية'},
    operations:{kicker:'العمليات المتاحة',title:'دعم عملي للإنتاج والتغليف',text:'تُؤكد قائمة العمليات الدقيقة وفقًا لتركيبتك ومكوناتك ومواصفات المنتج النهائي.',items:[['التركيب','تحضير التركيبة وخلط الدفعة'],['التعبئة','تعبئة العطر بالحجم المعتمد'],['الإحكام بالغشاء','وضع غشاء واقٍ عند تحديد ذلك'],['تجميع المكونات','تجميع المضخة والغطاء والعبوة'],['الوضع اليدوي في العلب','الوضع اليدوي وفحوص المظهر النهائي'],['التغليف النهائي','فحص العبوة النهائية والتعبئة في كراتين الشحن']]},
    faq:{kicker:'قبل طلب عرض سعر',title:'شروط مهمة للمشروع',text:'أرسل إلينا نوع المنتج والكمية والملفات أو العينات المتاحة كي يتمكن المصنع من تأكيد المسار الصحيح.',items:[['ما كميات البدء المعتادة؟','{{config.policies.moq}}'],['هل تعني مدة 5 أيام إجمالي وقت التسليم؟','لا. تشير مدة 5 أيام تقريبًا إلى شراء المواد الخام القياسية بعد تأكيد المشروع. أما إعداد العينات والعبوات المخصصة والإنتاج والفحص والشحن فتُجدول بصورة منفصلة.'],['هل يمكننا توريد موادنا أو عينة من المنتج؟','نعم. يمكننا مراجعة المواد أو الملفات الفنية أو المواصفات أو العينات المرجعية التي يقدمها العميل، وتحديد نطاق التصنيع التعاقدي بعد تقييم الجدوى.'],['ما العمليات التي يمكن للمصنع تنفيذها؟','تشمل العمليات المتاحة التركيب والتعبئة والإحكام بالغشاء وتجميع المكونات والتغليف والوضع اليدوي في العلب. وتعتمد القائمة المؤكدة على مواصفات المنتج.']]},
    final:{eyebrow:'ابدأ بالمعلومات المتوفرة لديك',title:'دع المصنع يوصي بنموذج التعاون المناسب',text:'شارك المنتج المستهدف والكمية التقديرية والوجهة وأي ملفات فنية أو تركيبة أو عينة مرجعية متاحة.',cta:'اطلب مراجعة المشروع'}
  },
  fr: {
    hero:{eyebrow:'Marque privée · OEM · ODM',title:'Choisissez le mode de fabrication adapté à votre projet de parfum',text:'Commencez avec un parfum existant et un conditionnement en stock, développez un produit personnalisé ou confiez-nous vos propres matières, fichiers graphiques ou échantillon de référence.',primary:'Discuter de votre projet',secondary:'Comparer les modèles de service'},
    factLabels:['MOQ habituel en marque privée','MOQ habituel pour un projet personnalisé','Approvisionnement standard en matières premières','Options de façonnage flexibles'], factValues:['{{fact("privateLabelMoq")}}','{{fact("customMoq")}}','Environ 5 jours','4 modèles'],
    routesIntro:{kicker:'Choisissez votre formule',title:'Trois façons concrètes de travailler avec notre usine',text:'Le modèle adapté dépend des éléments dont vous disposez déjà, du niveau de développement nécessaire et des composants à approvisionner ou à personnaliser.'},
    routes:[
      {id:'private-label',badge:'La formule la plus rapide',quantity:'Habituellement {{fact("privateLabelMoq")}}',title:'Marque privée',text:'Choisissez parmi les orientations olfactives existantes et les formats de flacons disponibles, puis appliquez la décoration et le conditionnement de votre propre marque.',details:[['Vous fournissez','Nom de la marque, fichiers graphiques et marché cible'],['L’usine prend en charge','Sélection du produit, remplissage, étiquetage, assemblage et emballage'],['Particulièrement adapté aux','Tests de marché, premiers lancements et collections de marque plus restreintes']],link:'Lancer un projet en marque privée'},
      {id:'odm',badge:'Développement personnalisé',quantity:'{{config.services.odm.moq.typicalPcs}}',title:'ODM / Projet personnalisé',text:'Développez un parfum et un conditionnement coordonné à partir de votre cahier des charges, avec des composants en stock ou personnalisés adaptés à la quantité et au budget approuvés.',details:[['Vous fournissez','Concept, orientation olfactive, budget et positionnement'],['L’usine prend en charge','Échantillonnage, approvisionnement des matières, composition, remplissage et emballage final'],['Particulièrement adapté aux','Collections de parfums originales et projets de marque différenciants']],link:'Discuter d’un projet personnalisé'},
      {id:'oem',badge:'Apports flexibles',quantity:'Selon le projet',title:'OEM / Façonnage à façon',text:'Fournissez votre formule, vos matières, votre cahier des charges technique, vos fichiers graphiques ou votre échantillon approuvé. Nous définissons le périmètre de production en fonction des éléments que vous apportez.',details:[['Vous fournissez','Formule, composants, fichiers graphiques, spécifications ou échantillon de référence'],['L’usine prend en charge','Les étapes convenues de façonnage, remplissage, assemblage, contrôle et emballage'],['Particulièrement adapté aux','Marques disposant déjà d’un standard produit ou d’une chaîne d’approvisionnement établis']],link:'Demander une étude OEM'}
    ],
    terms:'Les quantités initiales habituelles s’appliquent aux composants standard adaptés. Des séries pilotes plus petites peuvent être étudiées au cas par cas via WhatsApp, sans garantie d’acceptation. Des quantités inférieures peuvent limiter les choix de parfum, de flacon, de décoration et de conditionnement, et avoir une incidence sur le prix unitaire.',
    options:{kicker:'Coopération flexible',title:'Des options de façonnage adaptées à ce dont vous disposez déjà',text:'Avant d’établir le devis, nous confirmons la répartition des responsabilités concernant les formules, les matières premières, les composants de conditionnement et la production.',items:[['Façonnage à façon','Vous fournissez les matières ou composants convenus ; l’usine réalise les étapes de façonnage confirmées.','Matières fournies par le client'],['Production clé en main','Nous coordonnons les matières et la production approuvées, de l’achat des composants au remplissage et à l’emballage.','Matières + fabrication'],['Production selon fichiers graphiques ou spécifications','La production est organisée à partir de vos fichiers graphiques, plans et exigences techniques, après étude de faisabilité.','Fichiers de conception fournis par le client'],['Production selon un échantillon de référence','Fournissez un échantillon approuvé pour évaluation. Nous définissons les spécifications réalisables du parfum, du conditionnement et du procédé avant l’échantillonnage.','Référence fournie par le client']]},
    process:{kicker:'Du cahier des charges aux produits finis',title:'Un processus jalonné de validations claires',visualTitle:'Environnement de production réel',visualMeta:'Composition · Remplissage · Assemblage',items:[['Cahier des charges et choix de la formule','Confirmer le type de produit, la quantité, les éléments fournis, la destination, le budget et le niveau de personnalisation requis.'],['Devis et spécifications','Définir le modèle de coopération, le périmètre de production, les matières, les exigences qualité et les conditions commerciales.'],['Échantillonnage et revue des composants','Évaluer les échantillons de parfum, les flacons, les pompes, les capots, les fichiers graphiques et le conditionnement avant validation.'],['Validation finale','Figer la formule, les composants, les fichiers de décoration et la référence approuvée avant les achats et la production.'],['Approvisionnement en matières premières','L’achat des matières premières standard prend environ 5 jours après confirmation. Les composants personnalisés peuvent nécessiter un délai supplémentaire.'],['Production et contrôles en cours de fabrication','Réaliser les opérations convenues de composition, remplissage, scellage, assemblage et emballage, avec des points de contrôle.'],['Contrôle final et préparation de l’expédition','Confirmer l’emballage final, les informations de lot et les documents requis pour le mode de transport sélectionné.']]},
    samples:{kicker:'Évaluez avant de produire',title:'Coffret gratuit d’échantillons de parfums',intro:'Évaluez l’orientation olfactive avant de valider la production. Les échantillons d’évaluation de base sont fournis gratuitement ; seuls les frais réels de messagerie jusqu’à votre destination sont à votre charge.',mediaTitle:'Showroom d’échantillons de l’usine',mediaMeta:'Évaluation olfactive · Revue des composants',labels:['Coût des échantillons','Coffret habituel','Délai de préparation','Frais de messagerie'],values:['Gratuit','{{fact("sampleSet")}}','{{fact("sampleDays")}}','Coût réel'],notes:['Le tarif de messagerie est calculé en fonction de la destination et confirmé avec vous avant l’envoi.','Les formulations spéciales, les cycles de révision supplémentaires ou les échantillons de conditionnement personnalisé sont étudiés séparément si des frais additionnels s’appliquent.'],cta:'Demander des échantillons gratuits'},
    operations:{kicker:'Opérations disponibles',title:'Un soutien concret pour la production et l’emballage',text:'La liste précise des opérations est confirmée en fonction de votre formule, de vos composants et des spécifications du produit fini.',items:[['Composition','Préparation de la formule et mélange du lot'],['Remplissage','Remplissage du parfum au volume approuvé'],['Scellage sous film','Application d’un film protecteur lorsque cela est spécifié'],['Assemblage des composants','Assemblage de la pompe, du capot et du conditionnement'],['Mise en boîte manuelle','Placement manuel et contrôles de présentation'],['Emballage final','Contrôle du conditionnement fini et mise en cartons d’expédition']]},
    faq:{kicker:'Avant de demander un devis',title:'Conditions importantes du projet',text:'Envoyez-nous le type de produit, la quantité et les fichiers ou échantillons disponibles afin que l’usine puisse confirmer la formule adaptée.',items:[['Quelles sont les quantités initiales habituelles ?','{{config.policies.moq}}'],['Le délai de 5 jours correspond-il au délai total de livraison ?','Non. Les 5 jours environ correspondent à l’achat des matières premières standard après confirmation du projet. L’échantillonnage, le conditionnement personnalisé, la production, le contrôle et l’expédition font l’objet de calendriers distincts.'],['Pouvons-nous fournir nos propres matières ou un échantillon du produit ?','Oui. Nous pouvons étudier les matières, fichiers graphiques, spécifications ou échantillons de référence fournis par le client, puis définir le périmètre du façonnage à façon après évaluation de la faisabilité.'],['Quelles opérations l’usine peut-elle réaliser ?','Les opérations disponibles comprennent la composition, le remplissage, le scellage sous film, l’assemblage des composants, l’emballage et la mise en boîte manuelle. La liste confirmée dépend des spécifications du produit.']]},
    final:{eyebrow:'Commencez avec les informations dont vous disposez déjà',title:'Laissez l’usine vous recommander le modèle de coopération adapté',text:'Indiquez-nous le produit visé, la quantité estimée, la destination et tout fichier graphique, formule ou échantillon de référence disponible.',cta:'Demander une étude de projet'}
  }
};
